import { 
  BookOpen, Coffee, Lightbulb, Heart, Zap, Smile, Library, PenTool, User, RefreshCw, Brain, MessageCircle, List, Book
} from 'lucide-react';

// MoonIcon 컴포넌트 (데이터 파일에서 쓰기 위해 이동)
export const MoonIcon = (props) => (
    <svg
        {...props}
        xmlns="http://www.w3.org/2000/svg"
        width="24"
        height="24"
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        strokeWidth="2"
        strokeLinecap="round"
        strokeLinejoin="round"
    >
        <path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z" />
    </svg>
);

// 번역 데이터 (T)
export const T = {
  ko: {
    app_name: "오독\n오독",
    my_library: "보관함",
    welcome: "반갑습니다,",
    home_title: "오늘의 첫 독자가\n되어보시겠어요?",
    fiction: "소설",
    essay: "에세이",
    improvement: "자기계발",
    humanities: "인문교양",
    subgenre_anthology: "단행본 소설",
    subgenre_anthology_desc: "매일 새로운 주제의 단편",
    subgenre_series: "시리즈 소설",
    subgenre_series_desc: "독자와 함께 만드는 연재물",
    view_series: "기록된 시리즈 보기",
    generating: "집필 중...",
    open_library: "서재 열기",
    point_info_prefix: "생성 시 ",
    point_info_suffix: " 지급",
    author: "발행인",
    me: "나",
    favorites_count: "명",
    rating_title: "작품은 어떠셨나요?",
    rating_info: "평가+댓글 시 +1P",
    rating_1: "별로",
    rating_2: "좋아요",
    rating_3: "최고",
    comments_title: "댓글",
    comment_placeholder: "평점 후 댓글 작성 (+1P)",
    comment_placeholder_edit: "수정 중...",
    login_required: "로그인 필요",
    submit: "등록",
    update: "완료",
    reply: "답글",
    edit: "수정",
    replying_to: "님께 답글",
    cancel: "취소",
    profile_title: "프로필",
    nickname_placeholder: "닉네임 (최대 6자)",
    nickname_desc: "공백 포함 6자 이내",
    save_profile: "저장하기",
    empty_library_title: "텅 비었어요",
    empty_library_desc: "별표를 눌러 담아보세요.",
    empty_read_title: "아직 완독한 책이 없어요",
    empty_read_desc: "끝까지 읽고 '완독 완료'를 눌러보세요.",
    select_language: "언어 / Language",
    font_size: "글자 크기",
    fs_small: "작게",
    fs_medium: "보통",
    fs_large: "크게",
    fs_xlarge: "더 크게",
    just_now: "방금",
    minute_read: "분",
    chars: "자",
    today_first: "오늘의 집필권",
    library_prefix: "",
    library_suffix: " 서재",
    translating: "번역 중...",
    translate_error: "실패",
    daily_limit_reached: "일일 한도 초과",
    daily_limit_desc: "내일 다시 이용해주세요.",
    need_points: "포인트 부족 (2P)",
    free_gen_btn: "무료 집필 (+1P)",
    point_gen_btn: "포인트 집필 (-2P)",
    point_cost_info: "추가 생성 2P 소모",
    rating_required: "평점을 먼저 주세요!",
    report_btn: "신고",
    report_modal_title: "오류 신고",
    report_desc: "오타/문맥 오류를 알려주세요.\n내용 변경 요청은 반려됩니다.",
    report_placeholder: "예: 2문단 오타 신고합니다.",
    report_submit: "제출",
    reporting: "검토 중...",
    report_accepted: "수정 완료! +2P 지급",
    report_rejected: "반려되었습니다.",
    already_reported: "이미 신고함",
    tab_home: "홈",
    tab_library: "서재",
    tab_bookmarks: "보관함",
    tab_profile: "MY",
    gen_fail: "생성 실패. 잠시 후 다시 시도해주세요.",
    share_msg: "이 글은 [오독오독] 앱 설치 후 볼 수 있습니다.",
    share_fail: "공유 기능을 사용할 수 없습니다.",
    vote_title: "다음 화 결정하기",
    vote_continue: "계속 연재",
    vote_end: "완결 내기",
    vote_desc: "투표 결과에 따라 다음 화의 운명이 결정됩니다.",
    voted: "투표 완료",
    series_part: "부",
    series_final: "완결",
    series_limit_reached: "시리즈 참여 완료",
    series_limit_desc: "시리즈는 하루에 한 번만 참여할 수 있습니다.",
    notice_title: "공지사항",
    notice_empty: "등록된 공지사항이 없습니다.",
    recommend_title: "오늘은 뭘 읽을까?",
    recommend_desc: "기분이나 날씨에 딱 맞는 글을 찾아드려요.",
    mood_q: "지금 기분이 어떠신가요?",
    mood_healing: "지치고 힘들어요 💧",
    mood_bored: "심심해요 🥱",
    mood_growth: "성장하고 싶어요 🔥",
    mood_thinking: "생각에 잠기고 싶어요 🌙",
    season_recommend: "AI 자동 추천 (계절/날씨)",
    recommend_result: "당신을 위한 추천",
    go_to_read: "바로 읽으러 가기",
    rec_reason_healing: "지친 당신에게 따뜻한 위로를 전합니다.",
    rec_reason_bored: "흥미진진한 이야기로 지루함을 날려보세요.",
    rec_reason_growth: "더 나은 내일을 위한 영감을 드립니다.",
    rec_reason_thinking: "깊이 있는 사색의 시간을 가져보세요.",
    rec_reason_season: "지금 이 계절에 읽기 딱 좋은 글입니다.",
    level: "Lv.",
    exp: "경험치",
    max_level: "MAX",
    reading_exp: "독서 중... (+5 XP)",
    unlock_title: "이야기 잠금 해제",
    unlock_free: "오늘의 무료 열람권을 사용하시겠습니까?",
    unlock_paid: "2 포인트를 사용하여 잠금을 해제하시겠습니까?",
    unlock_btn_free: "무료로 읽기 (1/1)",
    unlock_btn_paid: "2P로 읽기",
    unlock_success: "잠금이 해제되었습니다!",
    unlock_fail_point: "포인트가 부족합니다.",
    finish_reading: "완독 완료!",
    finish_reading_q: "완독?",
    finish_reading_desc: "끝까지 읽으셨군요! (+10 XP)",
    read_already: "이미 완독한 책입니다.",
    read_more_time: "조금 더 읽어주세요 (최소 3분)",
    tab_fav: "즐겨찾기",
    tab_read: "서재 기록",
    attendance_check: "출석 체크 완료!",
    attendance_reward: "+1 Point 지급됨",
    weekly_stat: "주간 독서 리포트",
    stat_unit: "분",
    read_list_title: "완독한 책",
    help_title: "오독오독 사용설명서",
    help_btn: "사용설명서",
    help_basics: "기본 사용법",
    help_basics_desc: "1. 홈에서 원하는 장르를 선택하세요.\n2. 매일 새로운 책이 AI에 의해 생성됩니다.\n3. '오늘의 집필권'을 사용해 직접 책을 만들 수도 있습니다.",
    help_points: "포인트 & 레벨",
    help_points_desc: "- 책 생성: +50 XP (하루 최대 2회)\n- 독서: 1분당 +5 XP\n- 댓글/평점: +10 XP\n- 출석: +1 Point\n- 레벨업 시 새로운 칭호가 부여됩니다.",
    help_series: "시리즈 연재",
    help_series_desc: "시리즈 소설은 독자들의 투표로 연재가 결정됩니다. 2화부터 '연재' 또는 '완결'에 투표할 수 있습니다.",
    stories_count: "권의 책",
    google_login: "구글 계정으로 로그인",
    google_login_desc: "계정을 연동하면 데이터가 영구히 저장됩니다.",
    logout: "로그아웃",
    auth_domain_error: "Google login restricted in preview. (Works in local/deploy)"
  },
  en: {
    app_name: "Odok\nOdok",
    my_library: "Saved",
    welcome: "Hello,",
    home_title: "Be the first reader\nof the day.",
    fiction: "Fiction",
    essay: "Essay",
    improvement: "Self-Help",
    humanities: "Humanities",
    subgenre_anthology: "Anthology",
    subgenre_anthology_desc: "Daily new stories",
    subgenre_series: "Series",
    subgenre_series_desc: "Connected episodes",
    view_series: "View",
    generating: "Writing...",
    open_library: "Create",
    point_info_prefix: "Get ",
    point_info_suffix: " for creating",
    author: "Editor",
    me: "Me",
    favorites_count: "",
    rating_title: "Rate this story",
    rating_info: "+1P for rating & comment",
    rating_1: "Bad",
    rating_2: "Good",
    rating_3: "Great",
    comments_title: "Comments",
    comment_placeholder: "Rate first... (+1P)",
    comment_placeholder_edit: "Editing...",
    login_required: "Login needed",
    submit: "Post",
    update: "Done",
    reply: "Reply",
    edit: "Edit",
    replying_to: "To",
    cancel: "Cancel",
    profile_title: "Profile",
    nickname_placeholder: "Nickname (Max 6)",
    nickname_desc: "Max 6 chars",
    save_profile: "Save",
    empty_library_title: "Empty",
    empty_library_desc: "Tap star to save.",
    empty_read_title: "No finished books",
    empty_read_desc: "No finished books yet.", 
    select_language: "Language",
    font_size: "Font Size",
    fs_small: "Small",
    fs_medium: "Medium",
    fs_large: "Large",
    fs_xlarge: "X-Large",
    just_now: "Now",
    minute_read: "m",
    chars: "ch",
    today_first: "Create Story",
    library_prefix: "",
    library_suffix: "",
    translating: "Translating...",
    translate_error: "Error",
    daily_limit_reached: "Limit Reached",
    daily_limit_desc: "Try again tomorrow.",
    need_points: "Need 2P",
    free_gen_btn: "Free (+1P)",
    point_gen_btn: "Use 2P",
    point_cost_info: "Costs 2 Points",
    rating_required: "Rate first!",
    report_btn: "Report",
    report_modal_title: "Report Error",
    report_desc: "Typo/Context errors only.\nPlot changes rejected.",
    report_placeholder: "Ex: Typo in para 2...",
    report_submit: "Submit",
    reporting: "Reviewing...",
    report_accepted: "Fixed! +2P",
    report_rejected: "Rejected",
    already_reported: "Reported",
    tab_home: "Home",
    tab_library: "Library",
    tab_bookmarks: "Saved",
    tab_profile: "My",
    gen_fail: "Generation failed. Try again.",
    share_msg: "Install [Odok-Odok] app to read this story.",
    share_fail: "Share not supported.",
    vote_title: "Next Episode",
    vote_continue: "Extend",
    vote_end: "End Series",
    vote_desc: "Vote to decide the fate of the story.",
    voted: "Voted",
    series_part: "Part",
    series_final: "Final",
    series_limit_reached: "Series Limit",
    series_limit_desc: "You can only participate in Series once a day.",
    notice_title: "Notices",
    notice_empty: "No notices yet.",
    recommend_title: "What to read?",
    recommend_desc: "Let me find a perfect story for you.",
    mood_q: "How are you feeling?",
    mood_healing: "Exhausted 💧",
    mood_bored: "Bored 🥱",
    mood_growth: "Motivated 🔥",
    mood_thinking: "Thoughtful 🌙",
    season_recommend: "AI Pick (Season)",
    recommend_result: "Recommended for you",
    go_to_read: "Read Now",
    rec_reason_healing: "Comfort for your tired soul.",
    rec_reason_bored: "Fun story to kill boredom.",
    rec_reason_growth: "Inspiration for a better you.",
    rec_reason_thinking: "Time for deep thoughts.",
    rec_reason_season: "Perfect for this season.",
    level: "Lv.",
    exp: "EXP",
    max_level: "MAX",
    reading_exp: "Reading... (+5 XP)",
    unlock_title: "Unlock Story",
    unlock_free: "Use your daily free ticket?",
    unlock_paid: "Unlock for 2 Points?",
    unlock_btn_free: "Free Read (1/1)",
    unlock_btn_paid: "Use 2P",
    unlock_success: "Unlocked!",
    unlock_fail_point: "Not enough points.",
    finish_reading: "Finished",
    finish_reading_q: "Finish?",
    finish_reading_desc: "Great job! (+10 XP)",
    read_already: "Already finished.",
    read_more_time: "Read more (min 3 mins)",
    tab_fav: "Favorites",
    tab_read: "History",
    attendance_check: "Daily Check-in!",
    attendance_reward: "+1 Point Earned",
    weekly_stat: "Weekly Reading",
    stat_unit: "min",
    read_list_title: "Finished Books",
    help_title: "User Guide",
    help_btn: "Help",
    help_basics: "Basics",
    help_basics_desc: "1. Pick a genre.\n2. Read daily AI stories.\n3. Create your own story if it's not created yet.",
    help_points: "Points & Level",
    help_points_desc: "- Create: +50 XP\n- Read: +5 XP/min\n- Comment: +10 XP\n- Daily Check: +1 Point",
    help_series: "Series",
    help_series_desc: "Series fate is decided by votes. Vote to extend or end the story.",
    stories_count: "books",
    google_login: "Login with Google",
    google_login_desc: "Save your data permanently.",
    logout: "Log out",
    auth_domain_error: "Google login restricted in preview. (Works in local/deploy)"
  },
  ja: {
    app_name: "オドク\nオドク",
    my_library: "保存",
    welcome: "ようこそ、",
    home_title: "今日の最初の読者に\nなってみませんか？",
    fiction: "小説",
    essay: "随筆",
    improvement: "自己啓発",
    humanities: "人文教養",
    subgenre_anthology: "短編集",
    subgenre_anthology_desc: "毎日新しい物語",
    subgenre_series: "連載小説",
    subgenre_series_desc: "続くストーリー",
    view_series: "見る",
    generating: "執筆中...",
    open_library: "作成",
    point_info_prefix: "作成で",
    point_info_suffix: "獲得",
    author: "発行",
    me: "自分",
    favorites_count: "人",
    rating_title: "評価する",
    rating_info: "評価+コメで+1P",
    rating_1: "残念",
    rating_2: "良い",
    rating_3: "最高",
    comments_title: "コメント",
    comment_placeholder: "評価後に作成... (+1P)",
    comment_placeholder_edit: "修正中...",
    login_required: "要ログイン",
    submit: "登録",
    update: "完了",
    reply: "返信",
    edit: "修正",
    replying_to: "へ返信",
    cancel: "取消",
    profile_title: "設定",
    nickname_placeholder: "名前 (最大6文字)",
    nickname_desc: "6文字以内",
    save_profile: "保存",
    empty_library_title: "空っぽです",
    empty_library_desc: "星を押して保存",
    empty_read_title: "完読した本がありません",
    empty_read_desc: "まだ完読した本がありません。",
    select_language: "言語",
    font_size: "文字サイズ",
    fs_small: "小",
    fs_medium: "中",
    fs_large: "大",
    fs_xlarge: "特大",
    just_now: "今",
    minute_read: "分",
    chars: "字",
    today_first: "今日の執筆",
    library_prefix: "",
    library_suffix: " 書斎",
    translating: "翻訳中...",
    translate_error: "失敗",
    daily_limit_reached: "限度超過",
    daily_limit_desc: "また明日。",
    need_points: "2P不足",
    free_gen_btn: "無料 (+1P)",
    point_gen_btn: "2P使用",
    point_cost_info: "追加2P消費",
    rating_required: "評価してください",
    report_btn: "申告",
    report_modal_title: "エラー報告",
    report_desc: "誤字脱字のみ。\n内容変更は不可。",
    report_placeholder: "例：誤字あり...",
    report_submit: "提出",
    reporting: "審査中...",
    report_accepted: "修正完了! +2P",
    report_rejected: "却下",
    already_reported: "申告済み",
    tab_home: "ホーム",
    tab_library: "書斎",
    tab_bookmarks: "保存",
    tab_profile: "MY",
    gen_fail: "生成失敗。後ほど再試行してください。",
    share_msg: "[オドクオドク]アプリでのみ閲覧可能です。",
    share_fail: "共有できません。",
    vote_title: "次回を決定",
    vote_continue: "連載継続",
    vote_end: "完結させる",
    vote_desc: "投票で次の展開が決まります。",
    voted: "投票済み",
    series_part: "部",
    series_final: "完結",
    series_limit_reached: "参加完了",
    series_limit_desc: "連載小説への参加は1日1回までです。",
    notice_title: "お知らせ",
    notice_empty: "お知らせはありません.",
    recommend_title: "何を読もうかな？",
    recommend_desc: "気分や天気に合う文章を探します。",
    mood_q: "今の気分は？",
    mood_healing: "疲れ気味 💧",
    mood_bored: "退屈 🥱",
    mood_growth: "成長したい 🔥",
    mood_thinking: "考えたい 🌙",
    season_recommend: "AI 自動推薦 (季節)",
    recommend_result: "あなたへのおすすめ",
    go_to_read: "読みに行く",
    rec_reason_healing: "疲れたあなたへ、温かい慰めを。",
    rec_reason_bored: "退屈を吹き飛ばす面白い物語。",
    rec_reason_growth: "より良い明日へのインスピレーション。",
    rec_reason_thinking: "深い思索の時間を持ってみましょう。",
    rec_reason_season: "今の季節にぴったりの文章です。",
    level: "Lv.",
    exp: "経験値",
    tab_fav: "お気に入り",
    tab_read: "履歴",
    weekly_stat: "週間読書量",
    stat_unit: "分",
    read_list_title: "完読した本",
    help_title: "使い方ガイド",
    help_btn: "使い方",
    help_basics: "基本",
    help_basics_desc: "1. ジャンルを選択。\n2. 毎日AIが新しい本を生成。\n3. 自分で本を作ることも可能。",
    help_points: "ポイント＆レベル",
    help_points_desc: "- 作成: +50 XP\n- 読書: +5 XP/分\n- コメント: +10 XP\n- 出席: +1 P",
    help_series: "連載",
    help_series_desc: "連載の行方は投票で決まります。",
    stories_count: "冊",
    google_login: "Googleでログイン",
    google_login_desc: "データを永久に保存します。",
    logout: "ログアウト",
    auth_domain_error: "プレビュー環境ではGoogleログインが制限されています。（ローカル/配布環境では正常動作します）"
  }
};

// 장르 데이터 (genres)
export const genres = [
    { 
      id: 'fiction', 
      nameKey: 'fiction', 
      icon: <BookOpen className="w-5 h-5" />, 
      color: 'bg-blue-100 text-blue-600', 
      prompt: '일상적이고 따뜻한 단편 소설을 써줘.',
      hasSubGenre: true,
      subGenres: [
        { id: 'daily', name: '일상', icon: <Coffee className="w-5 h-5" />, prompt: '소소하고 따뜻한 일상 속의 이야기를 담백하게 써주세요.' },
        { id: 'emotion', name: '감정', icon: <Heart className="w-5 h-5" />, prompt: '인물의 섬세한 감정선을 따라가는 깊이 있는 이야기를 써주세요.' },
        { id: 'twist', name: '반전', icon: <Zap className="w-5 h-5" />, prompt: '평범하게 시작하지만 마지막에 놀라운 반전이 있는 이야기를 써주세요.' },
        { id: 'healing', name: '힐링', icon: <Smile className="w-5 h-5" />, prompt: '지친 마음을 위로해주는 따뜻하고 몽글몽글한 이야기를 써주세요.' },
        { id: 'series', name: '시리즈', icon: <Library className="w-5 h-5" />, prompt: '다음 화가 궁금해지는 몰입감 높은 연재 소설을 써주세요. (주제 랜덤)' }
      ]
    },
    { 
      id: 'essay', 
      nameKey: 'essay', 
      icon: <Coffee className="w-5 h-5" />, 
      color: 'bg-orange-100 text-orange-600', 
      prompt: '친구에게 말하듯 편안한 에세이를 써줘.',
      hasSubGenre: true,
      subGenres: [
        { id: 'empathy', name: '공감위로', icon: <Heart className="w-5 h-5" />, prompt: '힘든 하루를 보낸 이에게 건네는 따뜻한 위로의 글을 써주세요.' },
        { id: 'attitude', name: '삶의태도', icon: <PenTool className="w-5 h-5" />, prompt: '삶을 대하는 긍정적이고 성찰적인 태도에 대해 써주세요.' },
        { id: 'relation', name: '관계', icon: <User className="w-5 h-5" />, prompt: '가족, 친구, 연인 등 사람 사이의 관계에 대한 깊은 통찰을 담아주세요.' },
        { id: 'alone', name: '혼자만의 시간', icon: <MoonIcon className="w-5 h-5" />, prompt: '고독을 즐기는 법과 혼자 있는 시간의 소중함에 대해 써주세요.' }
      ]
    },
    { 
      id: 'improvement', 
      nameKey: 'improvement', 
      icon: <Lightbulb className="w-5 h-5" />, 
      color: 'bg-green-100 text-green-600', 
      prompt: '현실적인 자기계발 조언을 해줘.',
      hasSubGenre: true,
      subGenres: [
        { id: 'habit', name: '습관·루틴', icon: <RefreshCw className="w-5 h-5" />, prompt: '성공적인 삶을 위한 작은 습관과 루틴 형성법에 대해 조언해주세요.' },
        { id: 'mindset', name: '마인드셋', icon: <Brain className="w-5 h-5" />, prompt: '단단한 멘탈과 긍정적인 사고방식을 갖기 위한 마인드셋을 이야기해주세요.' },
        { id: 'communication', name: '인간관계·소통', icon: <MessageCircle className="w-5 h-5" />, prompt: '타인과 원활하게 소통하고 좋은 관계를 맺는 대화법과 처세술을 알려주세요.' },
        { id: 'life', name: '인생정리', icon: <List className="w-5 h-5" />, prompt: '복잡한 인생을 단순하게 정리하고 중요한 것에 집중하는 법을 알려주세요.' }
      ]
    },
    { 
      id: 'humanities', 
      nameKey: 'humanities', 
      icon: <Brain className="w-5 h-5" />, 
      color: 'bg-purple-100 text-purple-600', 
      prompt: '쉬운 인문학 이야기를 해줘.',
      hasSubGenre: true,
      subGenres: [
        { id: 'psychology', name: '생활형심리', icon: <Heart className="w-5 h-5" />, prompt: '일상 생활에서 겪는 문제들을 심리학적 관점에서 쉽고 재미있게 풀어주세요.' },
        { id: 'philosophy', name: '이야기철학', icon: <Book className="w-5 h-5" />, prompt: '어려운 철학 개념을 재미있는 옛날 이야기나 예시를 들어 쉽게 설명해주세요.' },
        { id: 'human', name: '인간이해', icon: <User className="w-5 h-5" />, prompt: '인간의 본성과 행동 원리에 대한 인문학적 통찰을 쉽게 전달해주세요.' },
        { id: 'thinking', name: '생각훈련', icon: <Lightbulb className="w-5 h-5" />, prompt: '논리적으로 생각하고 비판적으로 사고하는 힘을 기르는 방법을 알려주세요.' }
      ]
    }
];