import {
  BookOpen, Coffee, Lightbulb, Heart, Zap, Smile, Library, PenTool, User, RefreshCw, Brain, MessageCircle, List, Book
} from 'lucide-react';

// MoonIcon 컴포넌트 (데이터 파일에서 쓰기 위해 이동)
export const MoonIcon = (props) => (
  <svg
    {...props}
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <path d="M12 3a6 6 0 0 0 9 9 9 9 0 1 1-9-9Z" />
  </svg>
);

// 번역 데이터 (T)
export const T = {
  ko: {
    app_name: "오독\n오독",
    my_library: "보관함",
    welcome: "반갑습니다,",
    home_title: "오늘의 첫 독자가\n되어보시겠어요?",
    fiction: "소설",
    essay: "에세이",
    improvement: "자기계발",
    humanities: "인문교양",
    subgenre_anthology: "단행본 소설",
    subgenre_anthology_desc: "매일 새로운 주제의 단편",
    subgenre_series: "시리즈 소설",
    subgenre_series_desc: "독자와 함께 만드는 연재물",
    view_series: "기록된 시리즈 보기",
    generating: "집필 중...",
    open_library: "서재 열기",
    point_info_prefix: "생성 시 ",
    point_info_suffix: " 지급",
    author: "발행인",
    me: "나",
    favorites_count: "명",
    rating_title: "작품은 어떠셨나요?",
    rating_info: "평가+댓글 시 +1P",
    rating_1: "별로",
    rating_2: "좋아요",
    rating_3: "최고",
    comments_title: "댓글",
    comment_placeholder: "평점 후 댓글 작성 (+1P)",
    comment_placeholder_edit: "수정 중...",
    login_required: "로그인 필요",
    submit: "등록",
    update: "완료",
    reply: "답글",
    edit: "수정",
    replying_to: "님께 답글",
    cancel: "취소",
    profile_title: "프로필",
    nickname_placeholder: "닉네임 (최대 6자)",
    nickname_desc: "공백 포함 6자 이내",
    save_profile: "저장하기",
    empty_library_title: "텅 비었어요",
    empty_library_desc: "별표를 눌러 담아보세요.",
    empty_read_title: "아직 완독한 책이 없어요",
    empty_read_desc: "끝까지 읽고 '완독 완료'를 눌러보세요.",
    select_language: "언어 / Language",
    font_size: "글자 크기",
    fs_small: "작게",
    fs_medium: "보통",
    fs_large: "크게",
    fs_xlarge: "더 크게",
    just_now: "방금",
    minute_read: "분",
    chars: "자",
    today_first: "오늘의 집필권",
    library_prefix: "",
    library_suffix: " 서재",
    translating: "번역 중...",
    translate_error: "실패",
    daily_limit_reached: "일일 한도 초과",
    daily_limit_desc: "내일 다시 이용해주세요.",
    need_points: "포인트 부족 (2P)",
    free_gen_btn: "무료 집필 (+1P)",
    point_gen_btn: "포인트 집필 (-2P)",
    point_cost_info: "추가 생성 2P 소모",
    rating_required: "평점을 먼저 주세요!",
    report_btn: "신고",
    admin_delete_book: "책 삭제",
    admin_delete_confirm_title: "책 삭제",
    admin_delete_confirm_desc: "이 책을 삭제하면 복구할 수 없습니다. 신고된 불순 콘텐츠나 문제가 있는 책일 때만 삭제해주세요.",
    admin_delete_confirm: "삭제하기",
    admin_delete_fail: "삭제에 실패했습니다. 다시 시도해주세요.",
    admin_edit_content: "내용 수정",
    admin_save_content: "저장",
    admin_cancel_edit: "취소",
    admin_edit_success: "내용이 저장되었습니다.",
    admin_edit_fail: "저장에 실패했습니다. 다시 시도해주세요.",
    deleting: "삭제 중...",
    report_modal_title: "오류 신고",
    report_desc: "오타/문맥 오류를 알려주세요.\n내용 변경 요청은 반려됩니다.",
    report_placeholder: "예: 2문단 오타 신고합니다.",
    report_submit: "제출",
    reporting: "검토 중...",
    report_accepted: "수정 완료! +2P 지급",
    report_rejected: "반려되었습니다.",
    already_reported: "이미 신고함",
    tab_home: "홈",
    tab_library: "서재",
    tab_bookmarks: "보관함",
    tab_profile: "프로필",
    tab_write: "집필",
    gen_fail: "생성 실패. 잠시 후 다시 시도해주세요.",
    share_msg: "이 글은 [오독오독] 앱 설치 후 볼 수 있습니다.",
    share_fail: "공유 기능을 사용할 수 없습니다.",
    vote_title: "다음 화 결정하기",
    vote_continue: "계속 연재",
    vote_end: "완결 내기",
    vote_desc: "투표 결과에 따라 다음 화의 운명이 결정됩니다.",
    voted: "투표 완료",
    series_part: "부",
    series_final: "완결",
    series_limit_reached: "시리즈 참여 완료",
    series_limit_desc: "시리즈는 하루에 한 번만 참여할 수 있습니다.",
    notice_title: "공지사항",
    notice_empty: "등록된 공지사항이 없습니다.",
    recommend_title: "오늘은 뭘 읽을까?",
    recommend_desc: "기분이나 날씨에 딱 맞는 글을 찾아드려요.",
    mood_q: "지금 기분이 어떠신가요?",
    mood_healing: "지치고 힘들어요 💧",
    mood_bored: "심심해요 🥱",
    mood_growth: "성장하고 싶어요 🔥",
    mood_thinking: "생각에 잠기고 싶어요 🌙",
    season_recommend: "AI 자동 추천 (계절/날씨)",
    recommend_result: "당신을 위한 추천",
    go_to_read: "바로 읽으러 가기",
    rec_reason_healing: "지친 당신에게 따뜻한 위로를 전합니다.",
    rec_reason_bored: "흥미진진한 이야기로 지루함을 날려보세요.",
    rec_reason_growth: "더 나은 내일을 위한 영감을 드립니다.",
    rec_reason_thinking: "깊이 있는 사색의 시간을 가져보세요.",
    rec_reason_season: "지금 이 계절에 읽기 딱 좋은 글입니다.",
    level: "Lv.",
    exp: "경험치",
    max_level: "MAX",
    reading_exp: "독서 중... (+5 XP)",
    unlock_title: "이야기 잠금 해제",
    unlock_free: "오늘의 무료 열람권을 사용하시겠습니까?",
    unlock_paid: "2 포인트를 사용하여 잠금을 해제하시겠습니까?",
    unlock_btn_free: "무료로 읽기 (1/1)",
    unlock_btn_paid: "2P로 읽기",
    unlock_success: "잠금이 해제되었습니다!",
    unlock_fail_point: "포인트가 부족합니다.",
    finish_reading: "완독 완료!",
    finish_reading_q: "완독?",
    finish_reading_desc: "끝까지 읽으셨군요! (+10 XP)",
    read_already: "이미 완독한 책입니다.",
    read_more_time: "조금 더 읽어주세요 (최소 3분)",
    tab_fav: "즐겨찾기",
    tab_read: "서재 기록",
    attendance_check: "출석 체크 완료!",
    attendance_reward: "잉크 지급됨",
    ink: "잉크",
    weekly_stat: "주간 독서 리포트",
    stat_unit: "분",
    read_list_title: "완독한 책",
    help_title: "오독오독 사용설명서",
    help_btn: "사용 설명서",
    help_basics: "기본 사용법",
    help_basics_desc: "1. 홈에서 장르를 선택하고 오늘의 책을 읽거나, 집필 탭에서 직접 책을 쓸 수 있습니다.\n2. 1일 2회 집필 가능(첫 회 무료, 2회차 잉크 소모).\n3. 잉크는 출석·레벨업·집필 보상으로 얻고, 독서·추가 집필·홍보 등에 사용됩니다.",
    help_points: "포인트 & 레벨",
    help_points_desc: "- 잉크 1개 사용 시 10 XP 적립\n- 레벨업 시 잉크 5개 보너스\n- 출석: 레벨별 2~5개 잉크\n- 레벨에 따라 7단계 칭호(새싹→작가→숙련작가→베스트→스타→거장→마스터)가 부여되며, 책 표지에 칭호 아이콘으로 표시됩니다.",
    help_series: "시리즈 연재",
    help_series_desc: "시리즈는 누구나 다음 화를 이어 쓸 수 있는 릴레이 소설입니다. 2화부터 '연재' 또는 '완결'에 투표할 수 있으며, 시리즈는 하루에 한 번만 발행 가능합니다.",
    stories_count: "권의 책",
    google_login: "구글 계정으로 로그인",
    google_login_desc: "계정을 연동하면 데이터가 영구히 저장됩니다.",
    logout: "로그아웃",
    auth_domain_error: "Google login restricted in preview. (Works in local/deploy)",
    home_main_title: "하루 5분!\n이야기가 맛있어지는 시간",
    home_welcome: "{name}님 환영합니다!",
    guest: "게스트",
    home_new_books: "따끈따끈한 신작 🔥",
    home_weekly_best: "주간 베스트셀러 🏆",
    home_alltime_best: "누적 베스트셀러 📚",
    home_top_writers: "금주의 집필왕 👑",
    home_empty_new: "오늘의 첫 작가가 되어보세요!",
    home_empty_new_desc: "집필 탭에서 새로운 책을 만들어보세요",
    home_empty_best: "아직 집계된 베스트셀러가 없어요",
    home_empty_best_desc: "첫 번째 주인공이 되어보세요!",
    home_empty_alltime_best: "아직 누적 베스트셀러가 없어요",
    home_empty_alltime_best_desc: "독자들의 사랑을 받은 책이 여기에 올라갑니다",
    home_empty_writers: "아직 활동 중인 작가님이 없어요",
    weekly: "주간",
    total: "누적",
    author_by: "작가: {name}",
    ongoing: "연재",
    completed: "완결",
    in_app_browser_title: "외부 브라우저가 필요합니다",
    in_app_browser_desc: "구글 로그인을 위해 외부 브라우저로 접속해주세요.",
    notice_write_title: "공지사항 작성",
    title_placeholder: "제목",
    content_placeholder: "내용을 입력하세요...",
    saving: "저장 중...",
    write_complete: "작성 완료",
    ink_confirm_title: "잉크를 사용하시겠습니까?",
    ink_confirm_desc: "잉크 {amount}방울을 사용합니다.",
    watch_ad_read: "광고 보고 무료로 읽기",
    use_my_ink: "내 잉크 사용하기",
    close: "닫기",
    extra_write_title: "추가 집필",
    extra_write_desc: "{amount} 잉크를 사용하여 추가로 집필하시겠습니까?",
    write_btn: "집필",
    level_up_title: "축하합니다! 🎉",
    level_up_desc: "레벨 {level}이 되었습니다!",
    confirm: "확인",
    app_slogan: "나만의 책을 만들고 읽는 공간",
    google_start: "Google로 시작하기",
    reset_btn: "초기화",
    writing_complete_title: "집필이 완료되었습니다!",
    view_book_now: "생성소설 바로보기",
    stay: "머물기",
    items_count: "{count}건",
    write_limit_title: "오늘은 집필이 끝났어요",
    write_limit_desc: "하루 집필 가능 횟수(2회)를 모두 사용했습니다.",
    write_limit_reset_time: "내일 다시 집필할 수 있어요.",
    // Library
    library_title: "서재",
    library_desc: "모든 유저가 생성한 책들을 모아둔 곳입니다.",
    category_label: "카테고리 선택",
    view_all: "전체 보기",
    total_books: "총 {count}권",
    book_count_suffix: "권",
    search_placeholder: "책 제목 또는 작가로 검색...",
    all_months: "전체 기간",
    all_period: "전체",
    year_suffix: "년",
    month_suffix: "월",
    search_results: "검색 결과",
    clear_filter: "필터 초기화",
    no_search_results: "검색 결과가 없습니다",
    library_empty: "아직 등록된 책이 없습니다",
    library_empty_desc: "집필 탭에서 첫 책을 만들어보세요",
    anonymous: "익명",
    // Categories
    cat_webnovel: "웹소설",
    cat_novel: "소설",
    cat_series: "시리즈",
    cat_essay: "에세이",
    cat_self_help: "자기계발",
    cat_humanities: "인문/철학",
    // Write (Additional)
    write_title: "집필",
    write_desc: "원하는 장르를 선택하고 주제를 입력하면\nAI가 당신만의 책을 만들어줍니다.",
    select_category: "카테고리 선택",
    select_category_plz: "위에서 카테고리를 선택해주세요",
    // Archive
    archive_title: "보관함",
    archive_desc: "내가 작성한 책과 즐겨찾기한 책을 모아보세요.",
    my_books_tab: "내가 쓴 책",
    favorites_tab: "즐겨찾기",
    my_books_empty: "내가 쓴 책이 없습니다",
    favorites_empty: "즐겨찾기한 책이 없습니다",
    create_first_book: "첫 책을 만들어보세요",
    find_favorites: "마음에 드는 책을 찾아보세요",
    // Profile
    current_ink: "보유 잉크",
    get_ink_ad: "광고 보고 잉크 얻기 (+10)",
    nickname_label: "닉네임",
    nickname_label_required: "닉네임(필수)",
    anonymous_activity: "익명으로 활동",
    profile_photo: "프로필 사진",
    nickname_hint: "최초 1회는 자유롭게 변경 가능합니다",
    language_label: "언어 설정",
    font_size_label: "글자 크기 (본문 용)",
    theme_label: "테마",
    theme_light: "🌞 라이트",
    theme_dark: "🌙 다크",
    font_small: "작게",
    font_medium: "보통",
    font_large: "크게",
    font_xlarge: "더크게",
    account_management: "계정 관리",
    delete_account: "계정 탈퇴",
    save_btn: "저장",
    level: "LEVEL",
    next_level: "다음 레벨까지",
    next: "다음",
    title_grade_sprout: "새싹",
    title_grade_author: "작가",
    title_grade_skilled: "숙련 작가",
    title_grade_best: "베스트 작가",
    title_grade_star: "스타 작가",
    title_grade_grand: "거장",
    title_grade_master: "마스터",
    change_photo: "사진 변경",
    uploading: "업로드 중...",
    charging: "충전 중...",
    ink_charge_success: "+10 충전 완료!",
    delete_confirm_title: "계정 탈퇴",
    delete_confirm_desc: "정말로 계정을 탈퇴하시겠습니까?\n모든 데이터가 삭제되며 복구할 수 없습니다.",
    delete_btn: "탈퇴하기",
    cancel: "취소",
    generating_title: "집필 중입니다...",
    generating_desc: "책 생성에는 약 2~3분이 소요될 수 있어요.",
    generating_cancel_desc: "취소 후에 다른 작업을 진행할 수 있습니다.",
    hide_btn: "숨기기",
    cancel_write_btn: "집필 취소",
    // Write Details
    today_sold_out: "오늘의 {name} 마감",
    by_author: "By. {name}",
    start_writing: "집필하기",
    what_story: "어떤 이야기를 쓰고 싶으신가요?",
    refresh_keywords_free: "키워드 새로고침 (무료)",
    refresh_keywords_paid: "키워드 새로고침 (잉크 1)",
    book_title: "책 제목",
    title_placeholder: "15자 이내로 제목을 입력하세요",
    select_style: "스타일 선택",
    select_style_plz: "스타일을 선택하세요",
    writing_now: "책을 쓰고 있어요...",
    create_book: "책 생성하기",
    use_ink_create: "잉크 {cost} 사용하고 집필",
    sub_genre: "세부 장르",
    sub_type_webnovel: "웹소설형",
    sub_type_novel: "일반소설형",
    genre_label: "장르",
    mood_label: "분위기",
    mood_plz: "분위기를 선택하세요",
    pov_label: "누가 이야기하나요?",
    pov_plz: "시점을 선택하세요",
    pov_first_person: "내가 직접 말하기",
    pov_first_person_desc: "주인공이 자기 이야기를 하듯 생생하게 씁니다.",
    pov_third_limited: "옆에서 지켜보기",
    pov_third_limited_desc: "관찰자가 주인공의 행동을 보듯 설명합니다.",
    pov_omniscient: "전지적 시점",
    pov_omniscient_desc: "신처럼 모든 인물의 속마음까지 다 보여줍니다.",
    speech_tone_label: "어떤 말투로 쓸까요?",
    speech_tone_plz: "말투를 선택하세요",
    speech_tone_friendly: "친근한 말투",
    speech_tone_friendly_desc: '"~했어", "~였지"처럼 편안하게 이야기합니다.',
    speech_tone_formal: "단정한 말투",
    speech_tone_formal_desc: '"~했다", "~하였다"처럼 정통 소설의 느낌을 줍니다.',
    speech_tone_polite: "정중한 말투",
    speech_tone_polite_desc: '"~했습니다", "~입니다"처럼 차분하고 예의 바르게 씁니다.',
    dialogue_ratio_label: "대화가 얼마나 많은 게 좋을까요?",
    dialogue_ratio_plz: "대화 비중을 선택하세요",
    dialogue_ratio_heavy: "대화 중심 (웹소설 스타일)",
    dialogue_ratio_heavy_desc: "인물들의 대화가 많아 술술 읽히는 방식입니다.",
    dialogue_ratio_desc: "설명 중심 (일반 소설 스타일)",
    dialogue_ratio_desc_desc: "상황 묘사와 설명이 풍부하고 깊이 있는 방식입니다.",
    topic_keyword: "주제 또는 키워드",
    keyword_placeholder: "예: 가을 낙엽, 첫 사랑, 성장...",
    genre_romance: "로맨스",
    genre_romance_fantasy: "로맨스 판타지",
    genre_fantasy: "판타지",
    genre_modern_fantasy: "현대 판타지",
    genre_wuxia: "무협",
    genre_mystery_horror: "미스터리/공포",
    genre_sf: "SF",
    genre_drama: "드라마",
    genre_mystery: "미스터리/추리",
    genre_thriller: "스릴러",
    genre_history: "역사",
    genre_healing: "힐링",
    mood_soda: "사이다/먼치킨(압도적 힘)",
    mood_noir: "피폐/느와르(처절함)",
    mood_comic: "코믹/착각계(유쾌함)",
    mood_growth: "정통/성장형(감동)",
    mood_sweet: "달달/힐링(설렘)",
    mood_regret: "후회/집착(도파민)",
    mood_enemies: "혐관/배틀(티키타카)",
    mood_revenge: "사이다/복수(걸크러시)",
    mood_occult: "오컬트/기담(공포)",
    mood_slasher: "슬래셔/고어(잔혹)",
    mood_psychology: "두뇌전/심리(긴장감)",
    mood_lyric: "서정적/잔잔한",
    mood_realism: "현실적/사실주의",
    mood_tragic: "비극적/애절한",
    mood_intense: "격정적/파란만장",
    mood_down_to_earth: "담백한/현실연애",
    mood_classic_melo: "클래식/멜로",
    mood_first_love: "아련한/첫사랑",
    mood_hardboiled: "하드보일드/건조한",
    mood_mystery: "정통 추리/논리적",
    mood_philosophical: "철학적/사색적",
    mood_soda_desc: "주인공이 압도적인 힘으로 적을 제압하는 통쾌한 전개. 읽는 맛이 쏙쏙 느껴집니다.",
    mood_noir_desc: "어둡고 처절한 분위기. 하드보일드한 세계관과 절절한 감정선.",
    mood_comic_desc: "오해와 착각이 만들어내는 유쾌한 상황. 웃음 포인트가 많습니다.",
    mood_growth_desc: "주인공의 성장과 변화를 담은 감동적인 이야기. 여운이 오래 남습니다.",
    mood_sweet_desc: "달달하고 설레는 로맨스. 힐링과 두근거림이 함께합니다.",
    mood_regret_desc: "강렬한 감정과 집착. 중독성 있는 도파민 자극 전개.",
    mood_enemies_desc: "라이벌 관계의 티키타카와 반짝이는 대사. 말싸움의 묘미.",
    mood_revenge_desc: "주인공이 정의를 실현하는 통쾌한 복수극. 카타르시스 맛.",
    mood_occult_desc: "초자연적 존재와 기이한 이야기. 오싹한 공포 분위기.",
    mood_slasher_desc: "강렬한 공포와 잔혹한 묘사. 서스펜스가 높습니다.",
    mood_psychology_desc: "심리전과 추리가 주는 긴장감. 다음 장이 궁금해집니다.",
    mood_lyric_desc: "감성적이고 평화로운 문체. 마음을 정갈하게 다듬어 줍니다.",
    mood_realism_desc: "일상에 가까운 현실적인 서사. 공감을 이끌어냅니다.",
    mood_tragic_desc: "슬픔과 아픔이 담긴 감동적인 스토리. 가슴이 뭉클해집니다.",
    mood_intense_desc: "극적인 반전과 격렬한 감정선. 손에서 책을 놓기 어렵습니다.",
    mood_down_to_earth_desc: "현실적인 로맨스와 차분한 서술. 우리 옆에서 벌어질 법한 이야기.",
    mood_classic_melo_desc: "전통적인 멜로 드라마. 설렘과 눈물이 어우러집니다.",
    mood_first_love_desc: "첫사랑의 설레임과 아련함. 향수를 자극합니다.",
    mood_hardboiled_desc: "날카롭고 건조한 문체. 숨 막히는 긴장감.",
    mood_mystery_desc: "논리적 추리와 단서 배치. 추리의 재미를 선사합니다.",
    mood_philosophical_desc: "깊은 사유와 철학적 질문. 생각이 길어지는 이야기.",
    tone_essay_dry: "담백한/건조한",
    tone_essay_poetic: "감성적인/시적인",
    tone_essay_witty: "유머러스한/위트있는",
    tone_essay_colloquial: "친근한/구어체",
    tone_self_warm: "따뜻한 위로/격려",
    tone_self_motivation: "강한 동기부여/독설",
    tone_self_logical: "논리적인/분석적인",
    tone_self_experience: "경험담 위주",
    tone_humanities_questioning: "질문을 던지는/사색적인",
    tone_humanities_critical: "날카로운 비판",
    tone_humanities_dialogue: "대화 형식/인터뷰",
    tone_humanities_storytelling: "쉬운 해설/스토리텔링",
    ending_closed_happy: "닫힌 결말 (해피 엔딩)",
    ending_closed_sad: "닫힌 결말 (비극/새드 엔딩)",
    ending_open: "열린 결말 (여운을 남김)",
    ending_twist: "반전 결말 (충격적인 반전)",
    ending_bookend: "수미상관 (처음과 끝이 연결됨)",
    ending_style: "결말 스타일",
    ending_style_desc: "어떤 결말로 마무리할까요?",
    back: "뒤로",
    no_select: "선택 안 함",
    // Extra Write Modal
    extra_write_title: "추가 집필",
    extra_write_desc_2: "하루 무료 횟수를 사용했습니다.",
    extra_write_confirm: "{cost} 잉크를 사용하여 집필하시겠습니까?",
    current_hold: "현재 보유: {ink} 잉크",
    ad_write_free: "광고 보고 무료로 0.3초 집필",
    or: "또는",
    use_ink_btn: "잉크 {cost}개 쓰기",
    // Promotion
    promo_section_title: "작품 홍보",
    promo_button: "홍보하기",
    promo_active: "홍보 중",
    promo_modal_title: "작품 홍보",
    promo_input_placeholder: "홍보글을 입력하세요 (50자 이내)",
    promo_cost: "잉크 10개가 소모됩니다 (48시간)",
    promo_full: "홍보 자리가 모두 찼습니다. 잠시 후 다시 시도해주세요.",
    promo_already: "이미 홍보 중인 작품이 있습니다.",
    promo_ink_short: "잉크가 부족합니다 (필요: 10개)",
    promo_remaining: "남은 시간",
    promo_confirm: "홍보 시작",
    promo_hours: "시간",
    promo_minutes: "분",
    // Keyword Refresh Modal
    keyword_refresh_title: "키워드 새로고침",
    keyword_refresh_desc: "새로운 키워드 5개를 받아보세요.",
    refresh_ad_btn: "광고 보고 무료로 받기",
    refresh_ink_btn: "잉크 1개 사용하기",
    refresh_cancel: "취소",
    // Reader View
    view_count: "조회 {count}회",
    like_count_full: "좋아요 {count}회",
    favorite_count_full: "즐겨찾기 {count}회",
    complete_count_full: "완독 {count}회",
    like_btn: "좋아요",
    complete_btn: "완독",
    favorite_btn: "즐겨찾기",
    write_next_episode: "다음 화 집필하기",
    comment_count: "댓글 {count}개",
    first_comment: "첫 댓글을 남겨보세요.",
    comment_placeholder: "댓글을 입력하세요",
    comment_limit: "댓글은 200자 이내로 작성하세요.",
    no_content: "내용이 없습니다.",
    reading_completed: "완독됨",
    gift_level_limit: "선물하기는 레벨 6부터 가능해요",
    send_ink: "잉크쏘기",
    sending: "보내는 중...",
    send: "보내기",
    support_msg: "작품이 마음에 드셨다면 응원 한마디와 잉크를 쏴주세요",
    my_comment: "내 댓글",
    reply_to: "{name}에게 답글",
    edited: "수정됨",
    reply: "답글",
    edit: "수정",
    delete: "삭제",
    series_continue_title: "다음 화 전개 방식",
    series_continue_desc: "이야기를 어떻게 이어갈까요?",
    continue_series: "계속 연재 (이야기 확장)",
    finalize_series: "완결 짓기 (결말)",
    series_finalized: "시리즈가 완결되었습니다!",
    episode_added: "다음 화가 추가되었습니다!",
    // Write Details
    today_sold_out: "오늘의 {name} 마감",
    by_author: "By. {name}",
    start_writing: "집필하기",
    what_story: "어떤 이야기를 쓰고 싶으신가요?",
    refresh_keywords_free: "키워드 새로고침 (무료)",
    refresh_keywords_paid: "키워드 새로고침 (잉크 1)",
    book_title: "책 제목",
    title_placeholder: "15자 이내로 제목을 입력하세요",
    select_style: "스타일 선택",
    select_style_plz: "스타일을 선택하세요",
    writing_now: "책을 쓰고 있어요...",
    create_book: "책 생성하기",
    use_ink_create: "잉크 {cost} 사용하고 집필",
    sub_genre: "세부 장르",
    sub_type_webnovel: "웹소설형",
    sub_type_novel: "일반소설형",
    genre_label: "장르",
    mood_label: "분위기",
    mood_plz: "분위기를 선택하세요",
    pov_label: "누가 이야기하나요?",
    pov_plz: "시점을 선택하세요",
    pov_first_person: "내가 직접 말하기",
    pov_first_person_desc: "주인공이 자기 이야기를 하듯 생생하게 씁니다.",
    pov_third_limited: "옆에서 지켜보기",
    pov_third_limited_desc: "관찰자가 주인공의 행동을 보듯 설명합니다.",
    pov_omniscient: "전지적 시점",
    pov_omniscient_desc: "신처럼 모든 인물의 속마음까지 다 보여줍니다.",
    speech_tone_label: "어떤 말투로 쓸까요?",
    speech_tone_plz: "말투를 선택하세요",
    speech_tone_friendly: "친근한 말투",
    speech_tone_friendly_desc: '"~했어", "~였지"처럼 편안하게 이야기합니다.',
    speech_tone_formal: "단정한 말투",
    speech_tone_formal_desc: '"~했다", "~하였다"처럼 정통 소설의 느낌을 줍니다.',
    speech_tone_polite: "정중한 말투",
    speech_tone_polite_desc: '"~했습니다", "~입니다"처럼 차분하고 예의 바르게 씁니다.',
    dialogue_ratio_label: "대화가 얼마나 많은 게 좋을까요?",
    dialogue_ratio_plz: "대화 비중을 선택하세요",
    dialogue_ratio_heavy: "대화 중심 (웹소설 스타일)",
    dialogue_ratio_heavy_desc: "인물들의 대화가 많아 술술 읽히는 방식입니다.",
    dialogue_ratio_desc: "설명 중심 (일반 소설 스타일)",
    dialogue_ratio_desc_desc: "상황 묘사와 설명이 풍부하고 깊이 있는 방식입니다.",
    topic_keyword: "주제 또는 키워드",
    keyword_placeholder: "예: 가을 낙엽, 첫 사랑, 성장...",
    genre_romance: "로맨스",
    genre_romance_fantasy: "로맨스 판타지",
    genre_fantasy: "판타지",
    genre_modern_fantasy: "현대 판타지",
    genre_wuxia: "무협",
    genre_mystery_horror: "미스터리/공포",
    genre_sf: "SF",
    genre_drama: "드라마",
    genre_mystery: "미스터리/추리",
    genre_thriller: "스릴러",
    genre_history: "역사",
    genre_healing: "힐링",
    mood_soda: "사이다/먼치킨(압도적 힘)",
    mood_noir: "피폐/느와르(처절함)",
    mood_comic: "코믹/착각계(유쾌함)",
    mood_growth: "정통/성장형(감동)",
    mood_sweet: "달달/힐링(설렘)",
    mood_regret: "후회/집착(도파민)",
    mood_enemies: "혐관/배틀(티키타카)",
    mood_revenge: "사이다/복수(걸크러시)",
    mood_occult: "오컬트/기담(공포)",
    mood_slasher: "슬래셔/고어(잔혹)",
    mood_psychology: "두뇌전/심리(긴장감)",
    mood_lyric: "서정적/잔잔한",
    mood_realism: "현실적/사실주의",
    mood_tragic: "비극적/애절한",
    mood_intense: "격정적/파란만장",
    mood_down_to_earth: "담백한/현실연애",
    mood_classic_melo: "클래식/멜로",
    mood_first_love: "아련한/첫사랑",
    mood_hardboiled: "하드보일드/건조한",
    mood_mystery: "정통 추리/논리적",
    mood_philosophical: "철학적/사색적",
    mood_soda_desc: "주인공이 압도적인 힘으로 적을 제압하는 통쾌한 전개. 읽는 맛이 쏙쏙 느껴집니다.",
    mood_noir_desc: "어둡고 처절한 분위기. 하드보일드한 세계관과 절절한 감정선.",
    mood_comic_desc: "오해와 착각이 만들어내는 유쾌한 상황. 웃음 포인트가 많습니다.",
    mood_growth_desc: "주인공의 성장과 변화를 담은 감동적인 이야기. 여운이 오래 남습니다.",
    mood_sweet_desc: "달달하고 설레는 로맨스. 힐링과 두근거림이 함께합니다.",
    mood_regret_desc: "강렬한 감정과 집착. 중독성 있는 도파민 자극 전개.",
    mood_enemies_desc: "라이벌 관계의 티키타카와 반짝이는 대사. 말싸움의 묘미.",
    mood_revenge_desc: "주인공이 정의를 실현하는 통쾌한 복수극. 카타르시스 맛.",
    mood_occult_desc: "초자연적 존재와 기이한 이야기. 오싹한 공포 분위기.",
    mood_slasher_desc: "강렬한 공포와 잔혹한 묘사. 서스펜스가 높습니다.",
    mood_psychology_desc: "심리전과 추리가 주는 긴장감. 다음 장이 궁금해집니다.",
    mood_lyric_desc: "감성적이고 평화로운 문체. 마음을 정갈하게 다듬어 줍니다.",
    mood_realism_desc: "일상에 가까운 현실적인 서사. 공감을 이끌어냅니다.",
    mood_tragic_desc: "슬픔과 아픔이 담긴 감동적인 스토리. 가슴이 뭉클해집니다.",
    mood_intense_desc: "극적인 반전과 격렬한 감정선. 손에서 책을 놓기 어렵습니다.",
    mood_down_to_earth_desc: "현실적인 로맨스와 차분한 서술. 우리 옆에서 벌어질 법한 이야기.",
    mood_classic_melo_desc: "전통적인 멜로 드라마. 설렘과 눈물이 어우러집니다.",
    mood_first_love_desc: "첫사랑의 설레임과 아련함. 향수를 자극합니다.",
    mood_hardboiled_desc: "날카롭고 건조한 문체. 숨 막히는 긴장감.",
    mood_mystery_desc: "논리적 추리와 단서 배치. 추리의 재미를 선사합니다.",
    mood_philosophical_desc: "깊은 사유와 철학적 질문. 생각이 길어지는 이야기.",
    tone_essay_dry: "담백한/건조한",
    tone_essay_poetic: "감성적인/시적인",
    tone_essay_witty: "유머러스한/위트있는",
    tone_essay_colloquial: "친근한/구어체",
    tone_self_warm: "따뜻한 위로/격려",
    tone_self_motivation: "강한 동기부여/독설",
    tone_self_logical: "논리적인/분석적인",
    tone_self_experience: "경험담 위주",
    tone_humanities_questioning: "질문을 던지는/사색적인",
    tone_humanities_critical: "날카로운 비판",
    tone_humanities_dialogue: "대화 형식/인터뷰",
    tone_humanities_storytelling: "쉬운 해설/스토리텔링",
    ending_closed_happy: "닫힌 결말 (해피 엔딩)",
    ending_closed_sad: "닫힌 결말 (비극/새드 엔딩)",
    ending_open: "열린 결말 (여운을 남김)",
    ending_twist: "반전 결말 (충격적인 반전)",
    ending_bookend: "수미상관 (처음과 끝이 연결됨)",
    ending_style: "결말 스타일",
    ending_style_desc: "어떤 결말로 마무리할까요?",
    back: "뒤로",
    no_select: "선택 안 함",
    // Extra Write Modal
    extra_write_title: "추가 집필",
    extra_write_desc_2: "하루 무료 횟수를 사용했습니다.", // extra_write_desc already exists but confirm text
    extra_write_confirm: "{cost} 잉크를 사용하여 집필하시겠습니까?",
    current_hold: "현재 보유: {ink} 잉크",
    ad_write_free: "광고 보고 무료로 0.3초 집필",
    or: "또는",
    // Achievement
    achievement_title: "🏆 내 업적",
    achievement_unlocked: "업적 해제!",
    achievement_locked: "미해제",
    ach_first_write_title: "첫 집필",
    ach_first_write_desc: "첫 번째 책을 집필했습니다",
    ach_writer_5_title: "집필가",
    ach_writer_5_desc: "책 5권을 집필했습니다",
    ach_writer_10_title: "다작가",
    ach_writer_10_desc: "책 10권을 집필했습니다",
    ach_first_read_title: "첫 독서",
    ach_first_read_desc: "타인의 책을 처음 읽었습니다",
    ach_reader_5_title: "독서가",
    ach_reader_5_desc: "책 5권을 읽었습니다",
    ach_reader_10_title: "다독가",
    ach_reader_10_desc: "책 10권을 읽었습니다",
    ach_streak_3_title: "3일 연속 출석",
    ach_streak_3_desc: "3일 연속으로 출석했습니다",
    ach_streak_7_title: "7일 연속 출석",
    ach_streak_7_desc: "7일 연속으로 출석했습니다",
    ach_level_10_title: "레벨 10 달성",
    ach_level_10_desc: "레벨 10에 도달했습니다",
    ach_level_30_title: "레벨 30 달성",
    ach_level_30_desc: "레벨 30에 도달했습니다",
    ach_comment_5_title: "댓글 달인",
    ach_comment_5_desc: "댓글을 5개 작성했습니다",
    ach_ink_100_title: "잉크 마스터",
    ach_ink_100_desc: "잉크를 100방울 사용했습니다",
  },
  en: {
    app_name: "Odok\nOdok",
    my_library: "Saved",
    welcome: "Hello,",
    home_title: "Be the first reader\nof the day.",
    fiction: "Fiction",
    essay: "Essay",
    improvement: "Self-Help",
    humanities: "Humanities",
    subgenre_anthology: "Anthology",
    subgenre_anthology_desc: "Daily new stories",
    subgenre_series: "Series",
    subgenre_series_desc: "Connected episodes",
    view_series: "View",
    generating: "Writing...",
    open_library: "Create",
    point_info_prefix: "Get ",
    point_info_suffix: " for creating",
    author: "Editor",
    me: "Me",
    favorites_count: "",
    rating_title: "Rate this story",
    rating_info: "+1P for rating & comment",
    rating_1: "Bad",
    rating_2: "Good",
    rating_3: "Great",
    comments_title: "Comments",
    comment_placeholder: "Rate first... (+1P)",
    comment_placeholder_edit: "Editing...",
    login_required: "Login needed",
    submit: "Post",
    update: "Done",
    reply: "Reply",
    edit: "Edit",
    replying_to: "To",
    cancel: "Cancel",
    profile_title: "Profile",
    nickname_placeholder: "Nickname (Max 6)",
    nickname_desc: "Max 6 chars",
    save_profile: "Save",
    empty_library_title: "Empty",
    empty_library_desc: "Tap star to save.",
    empty_read_title: "No finished books",
    empty_read_desc: "No finished books yet.",
    select_language: "Language",
    font_size: "Font Size",
    fs_small: "Small",
    fs_medium: "Medium",
    fs_large: "Large",
    fs_xlarge: "X-Large",
    just_now: "Now",
    minute_read: "m",
    chars: "ch",
    today_first: "Create Story",
    library_prefix: "",
    library_suffix: "",
    translating: "Translating...",
    translate_error: "Error",
    daily_limit_reached: "Limit Reached",
    daily_limit_desc: "Try again tomorrow.",
    need_points: "Need 2P",
    free_gen_btn: "Free (+1P)",
    point_gen_btn: "Use 2P",
    point_cost_info: "Costs 2 Points",
    rating_required: "Rate first!",
    report_btn: "Report",
    admin_delete_book: "Delete Book",
    admin_delete_confirm_title: "Delete Book",
    admin_delete_confirm_desc: "This action cannot be undone. Only delete books with inappropriate content or policy violations.",
    admin_delete_confirm: "Delete",
    admin_delete_fail: "Failed to delete. Please try again.",
    admin_edit_content: "Edit content",
    admin_save_content: "Save",
    admin_cancel_edit: "Cancel",
    admin_edit_success: "Content saved.",
    admin_edit_fail: "Failed to save. Please try again.",
    deleting: "Deleting...",
    report_modal_title: "Report Error",
    report_desc: "Typo/Context errors only.\nPlot changes rejected.",
    report_placeholder: "Ex: Typo in para 2...",
    report_submit: "Submit",
    reporting: "Reviewing...",
    report_accepted: "Fixed! +2P",
    report_rejected: "Rejected",
    already_reported: "Reported",
    tab_home: "Home",
    tab_library: "Library",
    tab_bookmarks: "Saved",
    tab_profile: "Profile",
    tab_write: "Write",
    gen_fail: "Generation failed. Try again.",
    share_msg: "Install [Odok-Odok] app to read this story.",
    share_fail: "Share not supported.",
    vote_title: "Next Episode",
    vote_continue: "Extend",
    vote_end: "End Series",
    vote_desc: "Vote to decide the fate of the story.",
    voted: "Voted",
    series_part: "Part",
    series_final: "Final",
    series_limit_reached: "Series Limit",
    series_limit_desc: "You can only participate in Series once a day.",
    notice_title: "Notices",
    notice_empty: "No notices yet.",
    recommend_title: "What to read?",
    recommend_desc: "Let me find a perfect story for you.",
    mood_q: "How are you feeling?",
    mood_healing: "Exhausted 💧",
    mood_bored: "Bored 🥱",
    mood_growth: "Motivated 🔥",
    mood_thinking: "Thoughtful 🌙",
    season_recommend: "AI Pick (Season)",
    recommend_result: "Recommended for you",
    go_to_read: "Read Now",
    rec_reason_healing: "Comfort for your tired soul.",
    rec_reason_bored: "Fun story to kill boredom.",
    rec_reason_growth: "Inspiration for a better you.",
    rec_reason_thinking: "Time for deep thoughts.",
    rec_reason_season: "Perfect for this season.",

    exp: "EXP",
    max_level: "MAX",
    reading_exp: "Reading... (+5 XP)",
    unlock_title: "Unlock Story",
    unlock_free: "Use your daily free ticket?",
    unlock_paid: "Unlock for 2 Points?",
    unlock_btn_free: "Free Read (1/1)",
    unlock_btn_paid: "Use 2P",
    unlock_success: "Unlocked!",
    unlock_fail_point: "Not enough points.",
    finish_reading: "Finished",
    finish_reading_q: "Finish?",
    finish_reading_desc: "Great job! (+10 XP)",
    read_already: "Already finished.",
    read_more_time: "Read more (min 3 mins)",
    tab_fav: "Favorites",
    tab_read: "History",
    attendance_check: "Daily Check-in!",
    attendance_reward: "Ink Earned",
    ink: "Ink",
    weekly_stat: "Weekly Reading",
    stat_unit: "min",
    read_list_title: "Finished Books",
    help_title: "User Guide",
    help_btn: "Help",
    help_basics: "Basics",
    help_basics_desc: "1. Pick a genre.\n2. Read daily AI stories.\n3. Create your own story if it's not created yet.",
    help_points: "Points & Level",
    help_points_desc: "- Create: +50 XP\n- Read: +5 XP/min\n- Comment: +10 XP\n- Daily Check: +1 Point",
    help_series: "Series",
    help_series_desc: "Series fate is decided by votes. Vote to extend or end the story.",
    stories_count: "books",
    google_login: "Login with Google",
    google_login_desc: "Save your data permanently.",
    logout: "Log out",
    auth_domain_error: "Google login restricted in preview. (Works in local/deploy)",
    home_main_title: "5 mins a day!\nStory time made delicious",
    home_welcome: "Welcome, {name}!",
    guest: "Guest",
    home_new_books: "New Arrivals 🔥",
    home_weekly_best: "Weekly Best 🏆",
    home_alltime_best: "All-Time Bestsellers 📚",
    home_top_writers: "Top Writers 👑",
    home_empty_new: "Be the first author today!",
    home_empty_new_desc: "Create a new book in Write tab",
    home_empty_best: "No bestsellers yet",
    home_empty_best_desc: "Be the first star!",
    home_empty_alltime_best: "No all-time bestsellers yet",
    home_empty_alltime_best_desc: "Books loved by readers appear here",
    home_empty_writers: "No active writers yet",
    weekly: "Weekly",
    total: "Total",
    author_by: "Author: {name}",
    ongoing: "Ongoing",
    completed: "Completed",
    in_app_browser_title: "External Browser Required",
    in_app_browser_desc: "Please use an external browser for Google Login.",
    notice_write_title: "Write Notice",
    title_placeholder: "Title",
    content_placeholder: "Enter content...",
    saving: "Saving...",
    write_complete: "Post",
    ink_confirm_title: "Use Ink?",
    ink_confirm_desc: "Use {amount} Ink to read.",
    watch_ad_read: "Watch Ad to Read Free",
    use_my_ink: "Use My Ink",
    close: "Close",
    extra_write_title: "Continue Writing",
    extra_write_desc: "Use {amount} Ink to continue writing?",
    write_btn: "Write",
    level_up_title: "Congratulations! 🎉",
    level_up_desc: "You reached Level {level}!",
    confirm: "OK",
    app_slogan: "Create and Read Your Own Stories",
    google_start: "Start with Google",
    reset_btn: "Reset",
    writing_complete_title: "Writing Completed!",
    view_book_now: "Read Now",
    stay: "Stay",
    items_count: "{count} items",
    write_limit_title: "Daily Limit Reached",
    write_limit_desc: "You've used all 2 daily writes.",
    write_limit_reset_time: "You can write again tomorrow.",
    // Library
    library_title: "Library",
    library_desc: "Collection of books created by all users.",
    category_label: "Select Category",
    view_all: "View All",
    total_books: "{count} books",
    book_count_suffix: " books",
    search_placeholder: "Search by title or author...",
    all_months: "All Time",
    all_period: "All",
    year_suffix: "",
    month_suffix: "",
    search_results: "Search Results",
    clear_filter: "Clear Filter",
    no_search_results: "No results found",
    library_empty: "No books yet",
    library_empty_desc: "Create your first book in Write tab",
    anonymous: "Anonymous",
    // Categories
    cat_webnovel: "Webnovel",
    cat_novel: "Novel",
    cat_series: "Series",
    cat_essay: "Essay",
    cat_self_help: "Self-Help",
    cat_humanities: "Humanities",
    // Write (Additional)
    write_title: "Write",
    write_desc: "Choose a genre and topic,\nAI will write a book for you.",
    select_category: "Select Category",
    select_category_plz: "Please select a category above",
    // Archive
    archive_title: "Archive",
    archive_desc: "Your created books and favorites.",
    my_books_tab: "My Books",
    favorites_tab: "Favorites",
    my_books_empty: "No created books",
    favorites_empty: "No favorites yet",
    create_first_book: "Create your first book",
    find_favorites: "Discover books to read",
    // Profile
    current_ink: "Current Ink",
    get_ink_ad: "Watch Ad for Ink (+10)",
    nickname_label: "Nickname",
    nickname_label_required: "Nickname (Required)",
    anonymous_activity: "Anonymous activity",
    profile_photo: "Profile Photo",
    nickname_hint: "Change freely once.",
    language_label: "Language",
    font_size_label: "Font Size (Reader)",
    theme_label: "Theme",
    theme_light: "🌞 Light",
    theme_dark: "🌙 Dark",
    font_small: "Small",
    font_medium: "Medium",
    font_large: "Large",
    font_xlarge: "X-Large",
    account_management: "Account",
    delete_account: "Delete Account",
    save_btn: "Save",
    level: "LEVEL",
    next_level: "Next Level",
    next: "Next",
    title_grade_sprout: "Sprout",
    title_grade_author: "Author",
    title_grade_skilled: "Skilled Author",
    title_grade_best: "Best Author",
    title_grade_star: "Star Author",
    title_grade_grand: "Veteran",
    title_grade_master: "Master",
    change_photo: "Change Photo",
    uploading: "Uploading...",
    charging: "Charging...",
    ink_charge_success: "+10 added!",
    delete_confirm_title: "Delete Account",
    delete_confirm_desc: "Are you sure?\nAll data will be lost.",
    delete_btn: "Delete",
    cancel: "Cancel",
    generating_title: "Generating Book...",
    generating_desc: "It may take 2-3 minutes.",
    generating_cancel_desc: "You can cancel to do other things.",
    hide_btn: "Hide",
    cancel_write_btn: "Cancel Writing",
    // Write Details
    today_sold_out: "{name} Sold Out Today",
    by_author: "By. {name}",
    start_writing: "Start Writing",
    what_story: "What story do you want to write?",
    refresh_keywords_free: "Refresh Keywords (Free)",
    refresh_keywords_paid: "Refresh (1 Ink)",
    book_title: "Book Title",
    title_placeholder: "Enter title (max 15 chars)",
    select_style: "Select Style",
    select_style_plz: "Please select a style",
    writing_now: "Writing book...",
    create_book: "Create Book",
    use_ink_create: "Use {cost} Ink to Write",
    sub_genre: "Sub Genre",
    sub_type_webnovel: "Web novel style",
    sub_type_novel: "Classic novel style",
    genre_label: "Genre",
    mood_label: "Mood",
    mood_plz: "Select Mood",
    pov_label: "Who tells the story?",
    pov_plz: "Select point of view",
    pov_first_person: "First person (I tell it)",
    pov_first_person_desc: "The protagonist vividly narrates their own story.",
    pov_third_limited: "Third person (observe)",
    pov_third_limited_desc: "An observer describes the protagonist's actions.",
    pov_omniscient: "Omniscient",
    pov_omniscient_desc: "Shows all characters' inner thoughts like a god.",
    speech_tone_label: "What tone to use?",
    speech_tone_plz: "Select speech tone",
    speech_tone_friendly: "Casual/Friendly",
    speech_tone_friendly_desc: "Uses comfortable endings like '~했어', '~였지'.",
    speech_tone_formal: "Formal narrative",
    speech_tone_formal_desc: "Uses classic novel style like '~했다', '~하였다'.",
    speech_tone_polite: "Polite",
    speech_tone_polite_desc: "Uses respectful endings like '~했습니다', '~입니다'.",
    dialogue_ratio_label: "How much dialogue?",
    dialogue_ratio_plz: "Select dialogue ratio",
    dialogue_ratio_heavy: "Dialogue-heavy (Web novel style)",
    dialogue_ratio_heavy_desc: "Lots of character dialogue for easy, flowing reading.",
    dialogue_ratio_desc: "Description-heavy (Classic novel style)",
    dialogue_ratio_desc_desc: "Rich situation description and depth.",
    topic_keyword: "Topic or Keywords",
    keyword_placeholder: "e.g., Autumn leaves, First love...",
    genre_romance: "Romance",
    genre_romance_fantasy: "Romance Fantasy",
    genre_fantasy: "Fantasy",
    genre_modern_fantasy: "Modern Fantasy",
    genre_wuxia: "Wuxia",
    genre_mystery_horror: "Mystery/Horror",
    genre_sf: "SF",
    genre_drama: "Drama",
    genre_mystery: "Mystery/Thriller",
    genre_thriller: "Thriller",
    genre_history: "History",
    genre_healing: "Healing",
    mood_soda: "Power Fantasy (Satisfying)",
    mood_noir: "Noir (Dark & Gritty)",
    mood_comic: "Comedy/Misunderstanding",
    mood_growth: "Classic Growth (Touching)",
    mood_sweet: "Sweet/Healing (Romantic)",
    mood_regret: "Regret/Obsession (Dopamine)",
    mood_enemies: "Enemies to Lovers (Witty)",
    mood_revenge: "Revenge (Satisfying)",
    mood_occult: "Occult/Strange Tales (Horror)",
    mood_slasher: "Slasher/Gore (Brutal)",
    mood_psychology: "Psychological (Suspense)",
    mood_lyric: "Lyrical/Quiet",
    mood_realism: "Realistic",
    mood_tragic: "Tragic/Melancholic",
    mood_intense: "Intense/Dramatic",
    mood_down_to_earth: "Down-to-earth Romance",
    mood_classic_melo: "Classic Melodrama",
    mood_first_love: "First Love (Nostalgic)",
    mood_hardboiled: "Hardboiled (Dry)",
    mood_mystery: "Classic Mystery (Logical)",
    mood_philosophical: "Philosophical (Contemplative)",
    mood_soda_desc: "Satisfying power fantasy. The protagonist overwhelms enemies with sheer strength.",
    mood_noir_desc: "Dark and gritty atmosphere. Hardboiled world and intense emotions.",
    mood_comic_desc: "Misunderstandings create hilarious situations. Lots of laugh-out-loud moments.",
    mood_growth_desc: "Touching story of growth and change. Lingers in the mind.",
    mood_sweet_desc: "Sweet, heart-fluttering romance. Healing and excitement combined.",
    mood_regret_desc: "Intense emotions and obsession. Addictive, dopamine-driven plot.",
    mood_enemies_desc: "Enemies-to-lovers banter and sparkling dialogue. Witty verbal sparring.",
    mood_revenge_desc: "Satisfying revenge where the protagonist delivers justice. Pure catharsis.",
    mood_occult_desc: "Supernatural beings and strange tales. Creepy horror atmosphere.",
    mood_slasher_desc: "Intense horror and brutal descriptions. High suspense.",
    mood_psychology_desc: "Psychological battles and deduction. Keeps you guessing what happens next.",
    mood_lyric_desc: "Emotional and peaceful prose. Calms and polishes the mind.",
    mood_realism_desc: "Realistic, down-to-earth narrative. Evokes empathy.",
    mood_tragic_desc: "Moving story of sorrow and pain. Tugs at the heartstrings.",
    mood_intense_desc: "Dramatic twists and intense emotion. Hard to put down.",
    mood_down_to_earth_desc: "Realistic romance and calm narration. Feels like it could happen next door.",
    mood_classic_melo_desc: "Classic melodrama. Romance and tears intertwined.",
    mood_first_love_desc: "The thrill and nostalgia of first love.",
    mood_hardboiled_desc: "Sharp, dry prose. Breath-taking tension.",
    mood_mystery_desc: "Logical deduction and clue placement. The joy of solving the mystery.",
    mood_philosophical_desc: "Deep reflection and philosophical questions. A story that invites thought.",
    tone_essay_dry: "Dry/Plain",
    tone_essay_poetic: "Lyrical/Poetic",
    tone_essay_witty: "Humorous/Witty",
    tone_essay_colloquial: "Friendly/Colloquial",
    tone_self_warm: "Warm support/Encouragement",
    tone_self_motivation: "Strong motivation/Tough love",
    tone_self_logical: "Logical/Analytical",
    tone_self_experience: "Experience-based",
    tone_humanities_questioning: "Questioning/Contemplative",
    tone_humanities_critical: "Sharp critique",
    tone_humanities_dialogue: "Dialogue/Interview format",
    tone_humanities_storytelling: "Easy explanation/Storytelling",
    kw_essay_0: "Dawn", kw_essay_1: "Dusk", kw_essay_2: "First snow", kw_essay_3: "Rainy season", kw_essay_4: "Heat wave", kw_essay_5: "Late autumn", kw_essay_6: "Spring breeze", kw_essay_7: "Christmas", kw_essay_8: "New Year's Eve", kw_essay_9: "Monday morning", kw_essay_10: "Weekend afternoon", kw_essay_11: "Midsummer night", kw_essay_12: "Solar eclipse", kw_essay_13: "Birthday", kw_essay_14: "Anniversary",
    kw_essay_15: "Convenience store", kw_essay_16: "Alley", kw_essay_17: "Rooftop", kw_essay_18: "Subway", kw_essay_19: "Bus window", kw_essay_20: "Empty room", kw_essay_21: "Playground", kw_essay_22: "Library", kw_essay_23: "Bathhouse", kw_essay_24: "Laundromat", kw_essay_25: "Airport", kw_essay_26: "Train station", kw_essay_27: "Sea", kw_essay_28: "Forest path", kw_essay_29: "Cafe corner", kw_essay_30: "Used bookstore", kw_essay_31: "Market", kw_essay_32: "Street stall", kw_essay_33: "Elevator",
    kw_essay_34: "Mother", kw_essay_35: "Father", kw_essay_36: "Grandmother", kw_essay_37: "First love", kw_essay_38: "Unrequited love", kw_essay_39: "Old friend", kw_essay_40: "Coworker", kw_essay_41: "Pet", kw_essay_42: "Stray cat", kw_essay_43: "Stranger", kw_essay_44: "Teacher", kw_essay_45: "Neighbor", kw_essay_46: "Myself", kw_essay_47: "Ex-lover",
    kw_essay_48: "Old photo", kw_essay_49: "Diary", kw_essay_50: "Radio", kw_essay_51: "Umbrella", kw_essay_52: "Bicycle", kw_essay_53: "Sneakers", kw_essay_54: "Handwritten letter", kw_essay_55: "Perfume", kw_essay_56: "Coffee", kw_essay_57: "Instant noodles", kw_essay_58: "A drink", kw_essay_59: "Cigarette", kw_essay_60: "Bouquet", kw_essay_61: "Cactus", kw_essay_62: "Streetlight", kw_essay_63: "Earbuds", kw_essay_64: "Bankbook", kw_essay_65: "Passport",
    kw_essay_66: "Longing", kw_essay_67: "Regret", kw_essay_68: "Comfort", kw_essay_69: "Boredom", kw_essay_70: "Excitement", kw_essay_71: "Anxiety", kw_essay_72: "Relief", kw_essay_73: "Solitude", kw_essay_74: "Freedom", kw_essay_75: "Resignation", kw_essay_76: "Acceptance", kw_essay_77: "Parting", kw_essay_78: "Meeting", kw_essay_79: "Courage", kw_essay_80: "Lie", kw_essay_81: "Secret", kw_essay_82: "Promise", kw_essay_83: "Waiting", kw_essay_84: "Dream", kw_essay_85: "Daydreaming",
    kw_essay_86: "Sound of rain", kw_essay_87: "Smell of grass", kw_essay_88: "Smell of food", kw_essay_89: "Siren", kw_essay_90: "Piano melody", kw_essay_91: "Cold air", kw_essay_92: "Warm blanket", kw_essay_93: "Cicadas", kw_essay_94: "Crunching leaves",
    kw_self_0: "Miracle morning", kw_self_1: "Early rising", kw_self_2: "Reading", kw_self_3: "Writing", kw_self_4: "Exercise", kw_self_5: "Meditation", kw_self_6: "Cold shower", kw_self_7: "Journaling", kw_self_8: "Affirmation", kw_self_9: "Visualization", kw_self_10: "Tidying", kw_self_11: "Memo", kw_self_12: "Time management", kw_self_13: "Priority", kw_self_14: "Checklist",
    kw_self_15: "Self-esteem", kw_self_16: "Resilience", kw_self_17: "Grit", kw_self_18: "Positivity", kw_self_19: "Gratitude", kw_self_20: "Flow", kw_self_21: "Perseverance", kw_self_22: "Courage", kw_self_23: "Diligence", kw_self_24: "Moderation", kw_self_25: "Humility", kw_self_26: "Confidence", kw_self_27: "Responsibility", kw_self_28: "Initiative", kw_self_29: "Let go of perfectionism",
    kw_self_30: "Leadership", kw_self_31: "Followership", kw_self_32: "Negotiation", kw_self_33: "Persuasion", kw_self_34: "Public speaking", kw_self_35: "Planning", kw_self_36: "Marketing", kw_self_37: "Personal branding", kw_self_38: "Networking", kw_self_39: "Mentoring", kw_self_40: "Benchmarking", kw_self_41: "Side project", kw_self_42: "Startup", kw_self_43: "Promotion", kw_self_44: "Salary negotiation",
    kw_self_45: "Savings", kw_self_46: "Investment", kw_self_47: "Stocks", kw_self_48: "Real estate", kw_self_49: "Spending control", kw_self_50: "Budget", kw_self_51: "Financial freedom", kw_self_52: "FIRE", kw_self_53: "Wealth building", kw_self_54: "Seed money", kw_self_55: "Compound interest", kw_self_56: "Asset allocation",
    kw_self_57: "Burnout", kw_self_58: "Slump", kw_self_59: "Failure", kw_self_60: "Rejection", kw_self_61: "Criticism", kw_self_62: "Stress", kw_self_63: "Insomnia", kw_self_64: "Procrastination", kw_self_65: "Three-day resolution", kw_self_66: "Inferiority", kw_self_67: "Jealousy", kw_self_68: "Lethargy", kw_self_69: "Trauma", kw_self_70: "Digital detox",
    kw_self_71: "Minimalist life", kw_self_72: "Work-life balance", kw_self_73: "Digital nomad", kw_self_74: "Side hustle", kw_self_75: "Lifelong learning", kw_self_76: "Language study", kw_self_77: "Certification", kw_self_78: "Hobby", kw_self_79: "Diet", kw_self_80: "Health",
    kw_hum_0: "Who am I", kw_hum_1: "Self", kw_hum_2: "Unconscious", kw_hum_3: "Desire", kw_hum_4: "Instinct", kw_hum_5: "Reason", kw_hum_6: "Emotion", kw_hum_7: "Memory", kw_hum_8: "Forgetting", kw_hum_9: "Dream", kw_hum_10: "Body", kw_hum_11: "Soul", kw_hum_12: "Death", kw_hum_13: "Aging", kw_hum_14: "Birth", kw_hum_15: "Growth", kw_hum_16: "Genius", kw_hum_17: "Madness",
    kw_hum_18: "Others", kw_hum_19: "Love", kw_hum_20: "Friendship", kw_hum_21: "Family", kw_hum_22: "Community", kw_hum_23: "Solitude", kw_hum_24: "Alienation", kw_hum_25: "Hatred", kw_hum_26: "Discrimination", kw_hum_27: "Equality", kw_hum_28: "Justice", kw_hum_29: "Law", kw_hum_30: "Power", kw_hum_31: "Politics", kw_hum_32: "War", kw_hum_33: "Peace", kw_hum_34: "Capitalism", kw_hum_35: "Labor", kw_hum_36: "Ownership",
    kw_hum_37: "Happiness", kw_hum_38: "Unhappiness", kw_hum_39: "Freedom", kw_hum_40: "Fate", kw_hum_41: "Chance", kw_hum_42: "Necessity", kw_hum_43: "Truth", kw_hum_44: "Falsehood", kw_hum_45: "Good and evil", kw_hum_46: "Morality", kw_hum_47: "Ethics", kw_hum_48: "Religion", kw_hum_49: "God", kw_hum_50: "Salvation", kw_hum_51: "Faith", kw_hum_52: "Doubt", kw_hum_53: "Hope", kw_hum_54: "Despair",
    kw_hum_55: "Time", kw_hum_56: "Eternity", kw_hum_57: "Moment", kw_hum_58: "Past", kw_hum_59: "Future", kw_hum_60: "Present", kw_hum_61: "History", kw_hum_62: "Universe", kw_hum_63: "Nature", kw_hum_64: "Environment", kw_hum_65: "Technology", kw_hum_66: "AI", kw_hum_67: "Artificial intelligence", kw_hum_68: "Virtual reality", kw_hum_69: "Evolution", kw_hum_70: "Extinction",
    kw_hum_71: "Beauty", kw_hum_72: "Ugliness", kw_hum_73: "Art", kw_hum_74: "Creation", kw_hum_75: "Destruction", kw_hum_76: "Inspiration", kw_hum_77: "Imitation", kw_hum_78: "Originality", kw_hum_79: "Taste", kw_hum_80: "Trend", kw_hum_81: "Classic", kw_hum_82: "Romantic", kw_hum_83: "Nihilism", kw_hum_84: "Absurdity", kw_hum_85: "Silence", kw_hum_86: "Language",
    ending_closed_happy: "Closed ending (Happy)",
    ending_closed_sad: "Closed ending (Tragic/Sad)",
    ending_open: "Open ending (Lingering)",
    ending_twist: "Twist ending (Shocking)",
    ending_bookend: "Bookend (Beginning & end connect)",
    ending_style: "Ending Style",
    ending_style_desc: "How should the story end?",
    back: "Back",
    no_select: "None",
    // Extra Write Modal
    extra_write_title: "Extra Write",
    extra_write_desc_2: "You used your free daily writes.",
    extra_write_confirm: "Use {cost} Ink to write more?",
    current_hold: "Current: {ink} Ink",
    ad_write_free: "Watch Ad to Write Free",
    or: "OR",
    use_ink_btn: "Use {cost} Ink",
    // Promotion
    promo_section_title: "Featured Books",
    promo_button: "Promote",
    promo_active: "Promoting",
    promo_modal_title: "Promote Book",
    promo_input_placeholder: "Enter promo text (max 50 chars)",
    promo_cost: "Costs 10 ink (48 hours)",
    promo_full: "All promo slots are full. Please try again later.",
    promo_already: "You already have a promoted book.",
    promo_ink_short: "Not enough ink (need: 10)",
    promo_remaining: "Time left",
    promo_confirm: "Start Promotion",
    promo_hours: "h",
    promo_minutes: "m",
    // Keyword Refresh Modal
    keyword_refresh_title: "Refresh Keywords",
    keyword_refresh_desc: "Get 5 new keywords.",
    refresh_ad_btn: "Watch Ad for Free",
    refresh_ink_btn: "Use 1 Ink",
    refresh_cancel: "Cancel",
    // Reader View
    view_count: "{count} Views",
    like_count_full: "{count} Likes",
    favorite_count_full: "{count} Favorites",
    complete_count_full: "{count} Completions",
    like_btn: "Like",
    complete_btn: "Complete",
    favorite_btn: "Favorite",
    write_next_episode: "Write Next Episode",
    comment_count: "{count} Comments",
    first_comment: "Be the first to comment.",
    comment_placeholder: "Enter your comment",
    comment_limit: "Maximum 200 characters.",
    no_content: "No content.",
    reading_completed: "Read",
    gift_level_limit: "Unlock gifting at Lv.6",
    send_ink: "Send Ink",
    sending: "Sending...",
    send: "Send",
    support_msg: "Support author with Ink!",
    my_comment: "Me",
    reply_to: "To {name}",
    edited: "Edited",
    reply: "Reply",
    edit: "Edit",
    delete: "Delete",
    series_continue_title: "Continue Story",
    series_continue_desc: "How should it proceed?",
    continue_series: "Extend Story",
    finalize_series: "Finalize (Ending)",
    series_finalized: "Series Completed!",
    episode_added: "Episode Added!",
    // Write Details
    today_sold_out: "{name} Sold Out Today",
    by_author: "By. {name}",
    start_writing: "Start Writing",
    what_story: "What story do you want to write?",
    refresh_keywords_free: "Refresh Keywords (Free)",
    refresh_keywords_paid: "Refresh (1 Ink)",
    book_title: "Book Title",
    title_placeholder: "Enter title (max 15 chars)",
    select_style: "Select Style",
    select_style_plz: "Please select a style",
    writing_now: "Writing book...",
    create_book: "Create Book",
    use_ink_create: "Use {cost} Ink to Write",
    sub_genre: "Sub Genre",
    sub_type_webnovel: "Web novel style",
    sub_type_novel: "Classic novel style",
    genre_label: "Genre",
    mood_label: "Mood",
    mood_plz: "Select Mood",
    pov_label: "Who tells the story?",
    pov_plz: "Select point of view",
    pov_first_person: "First person (I tell it)",
    pov_first_person_desc: "The protagonist vividly narrates their own story.",
    pov_third_limited: "Third person (observe)",
    pov_third_limited_desc: "An observer describes the protagonist's actions.",
    pov_omniscient: "Omniscient",
    pov_omniscient_desc: "Shows all characters' inner thoughts like a god.",
    speech_tone_label: "What tone to use?",
    speech_tone_plz: "Select speech tone",
    speech_tone_friendly: "Casual/Friendly",
    speech_tone_friendly_desc: "Uses comfortable endings like '~했어', '~였지'.",
    speech_tone_formal: "Formal narrative",
    speech_tone_formal_desc: "Uses classic novel style like '~했다', '~하였다'.",
    speech_tone_polite: "Polite",
    speech_tone_polite_desc: "Uses respectful endings like '~했습니다', '~입니다'.",
    dialogue_ratio_label: "How much dialogue?",
    dialogue_ratio_plz: "Select dialogue ratio",
    dialogue_ratio_heavy: "Dialogue-heavy (Web novel style)",
    dialogue_ratio_heavy_desc: "Lots of character dialogue for easy, flowing reading.",
    dialogue_ratio_desc: "Description-heavy (Classic novel style)",
    dialogue_ratio_desc_desc: "Rich situation description and depth.",
    topic_keyword: "Topic or Keywords",
    keyword_placeholder: "e.g., Autumn leaves, First love...",
    genre_romance: "Romance",
    genre_romance_fantasy: "Romance Fantasy",
    genre_fantasy: "Fantasy",
    genre_modern_fantasy: "Modern Fantasy",
    genre_wuxia: "Wuxia",
    genre_mystery_horror: "Mystery/Horror",
    genre_sf: "SF",
    genre_drama: "Drama",
    genre_mystery: "Mystery/Thriller",
    genre_thriller: "Thriller",
    genre_history: "History",
    genre_healing: "Healing",
    mood_soda: "Power Fantasy (Satisfying)",
    mood_noir: "Noir (Dark & Gritty)",
    mood_comic: "Comedy/Misunderstanding",
    mood_growth: "Classic Growth (Touching)",
    mood_sweet: "Sweet/Healing (Romantic)",
    mood_regret: "Regret/Obsession (Dopamine)",
    mood_enemies: "Enemies to Lovers (Witty)",
    mood_revenge: "Revenge (Satisfying)",
    mood_occult: "Occult/Strange Tales (Horror)",
    mood_slasher: "Slasher/Gore (Brutal)",
    mood_psychology: "Psychological (Suspense)",
    mood_lyric: "Lyrical/Quiet",
    mood_realism: "Realistic",
    mood_tragic: "Tragic/Melancholic",
    mood_intense: "Intense/Dramatic",
    mood_down_to_earth: "Down-to-earth Romance",
    mood_classic_melo: "Classic Melodrama",
    mood_first_love: "First Love (Nostalgic)",
    mood_hardboiled: "Hardboiled (Dry)",
    mood_mystery: "Classic Mystery (Logical)",
    mood_philosophical: "Philosophical (Contemplative)",
    mood_soda_desc: "Satisfying power fantasy. The protagonist overwhelms enemies with sheer strength.",
    mood_noir_desc: "Dark and gritty atmosphere. Hardboiled world and intense emotions.",
    mood_comic_desc: "Misunderstandings create hilarious situations. Lots of laugh-out-loud moments.",
    mood_growth_desc: "Touching story of growth and change. Lingers in the mind.",
    mood_sweet_desc: "Sweet, heart-fluttering romance. Healing and excitement combined.",
    mood_regret_desc: "Intense emotions and obsession. Addictive, dopamine-driven plot.",
    mood_enemies_desc: "Enemies-to-lovers banter and sparkling dialogue. Witty verbal sparring.",
    mood_revenge_desc: "Satisfying revenge where the protagonist delivers justice. Pure catharsis.",
    mood_occult_desc: "Supernatural beings and strange tales. Creepy horror atmosphere.",
    mood_slasher_desc: "Intense horror and brutal descriptions. High suspense.",
    mood_psychology_desc: "Psychological battles and deduction. Keeps you guessing what happens next.",
    mood_lyric_desc: "Emotional and peaceful prose. Calms and polishes the mind.",
    mood_realism_desc: "Realistic, down-to-earth narrative. Evokes empathy.",
    mood_tragic_desc: "Moving story of sorrow and pain. Tugs at the heartstrings.",
    mood_intense_desc: "Dramatic twists and intense emotion. Hard to put down.",
    mood_down_to_earth_desc: "Realistic romance and calm narration. Feels like it could happen next door.",
    mood_classic_melo_desc: "Classic melodrama. Romance and tears intertwined.",
    mood_first_love_desc: "The thrill and nostalgia of first love.",
    mood_hardboiled_desc: "Sharp, dry prose. Breath-taking tension.",
    mood_mystery_desc: "Logical deduction and clue placement. The joy of solving the mystery.",
    mood_philosophical_desc: "Deep reflection and philosophical questions. A story that invites thought.",
    tone_essay_dry: "Dry/Plain",
    tone_essay_poetic: "Lyrical/Poetic",
    tone_essay_witty: "Humorous/Witty",
    tone_essay_colloquial: "Friendly/Colloquial",
    tone_self_warm: "Warm support/Encouragement",
    tone_self_motivation: "Strong motivation/Tough love",
    tone_self_logical: "Logical/Analytical",
    tone_self_experience: "Experience-based",
    tone_humanities_questioning: "Questioning/Contemplative",
    tone_humanities_critical: "Sharp critique",
    tone_humanities_dialogue: "Dialogue/Interview format",
    tone_humanities_storytelling: "Easy explanation/Storytelling",
    kw_essay_0: "Dawn", kw_essay_1: "Dusk", kw_essay_2: "First snow", kw_essay_3: "Rainy season", kw_essay_4: "Heat wave", kw_essay_5: "Late autumn", kw_essay_6: "Spring breeze", kw_essay_7: "Christmas", kw_essay_8: "New Year's Eve", kw_essay_9: "Monday morning", kw_essay_10: "Weekend afternoon", kw_essay_11: "Midsummer night", kw_essay_12: "Solar eclipse", kw_essay_13: "Birthday", kw_essay_14: "Anniversary",
    kw_essay_15: "Convenience store", kw_essay_16: "Alley", kw_essay_17: "Rooftop", kw_essay_18: "Subway", kw_essay_19: "Bus window", kw_essay_20: "Empty room", kw_essay_21: "Playground", kw_essay_22: "Library", kw_essay_23: "Bathhouse", kw_essay_24: "Laundromat", kw_essay_25: "Airport", kw_essay_26: "Train station", kw_essay_27: "Sea", kw_essay_28: "Forest path", kw_essay_29: "Cafe corner", kw_essay_30: "Used bookstore", kw_essay_31: "Market", kw_essay_32: "Street stall", kw_essay_33: "Elevator",
    kw_essay_34: "Mother", kw_essay_35: "Father", kw_essay_36: "Grandmother", kw_essay_37: "First love", kw_essay_38: "Unrequited love", kw_essay_39: "Old friend", kw_essay_40: "Coworker", kw_essay_41: "Pet", kw_essay_42: "Stray cat", kw_essay_43: "Stranger", kw_essay_44: "Teacher", kw_essay_45: "Neighbor", kw_essay_46: "Myself", kw_essay_47: "Ex-lover",
    kw_essay_48: "Old photo", kw_essay_49: "Diary", kw_essay_50: "Radio", kw_essay_51: "Umbrella", kw_essay_52: "Bicycle", kw_essay_53: "Sneakers", kw_essay_54: "Handwritten letter", kw_essay_55: "Perfume", kw_essay_56: "Coffee", kw_essay_57: "Instant noodles", kw_essay_58: "A drink", kw_essay_59: "Cigarette", kw_essay_60: "Bouquet", kw_essay_61: "Cactus", kw_essay_62: "Streetlight", kw_essay_63: "Earbuds", kw_essay_64: "Bankbook", kw_essay_65: "Passport",
    kw_essay_66: "Longing", kw_essay_67: "Regret", kw_essay_68: "Comfort", kw_essay_69: "Boredom", kw_essay_70: "Excitement", kw_essay_71: "Anxiety", kw_essay_72: "Relief", kw_essay_73: "Solitude", kw_essay_74: "Freedom", kw_essay_75: "Resignation", kw_essay_76: "Acceptance", kw_essay_77: "Parting", kw_essay_78: "Meeting", kw_essay_79: "Courage", kw_essay_80: "Lie", kw_essay_81: "Secret", kw_essay_82: "Promise", kw_essay_83: "Waiting", kw_essay_84: "Dream", kw_essay_85: "Daydreaming",
    kw_essay_86: "Sound of rain", kw_essay_87: "Smell of grass", kw_essay_88: "Smell of food", kw_essay_89: "Siren", kw_essay_90: "Piano melody", kw_essay_91: "Cold air", kw_essay_92: "Warm blanket", kw_essay_93: "Cicadas", kw_essay_94: "Crunching leaves",
    kw_self_0: "Miracle morning", kw_self_1: "Early rising", kw_self_2: "Reading", kw_self_3: "Writing", kw_self_4: "Exercise", kw_self_5: "Meditation", kw_self_6: "Cold shower", kw_self_7: "Journaling", kw_self_8: "Affirmation", kw_self_9: "Visualization", kw_self_10: "Tidying", kw_self_11: "Memo", kw_self_12: "Time management", kw_self_13: "Priority", kw_self_14: "Checklist",
    kw_self_15: "Self-esteem", kw_self_16: "Resilience", kw_self_17: "Grit", kw_self_18: "Positivity", kw_self_19: "Gratitude", kw_self_20: "Flow", kw_self_21: "Perseverance", kw_self_22: "Courage", kw_self_23: "Diligence", kw_self_24: "Moderation", kw_self_25: "Humility", kw_self_26: "Confidence", kw_self_27: "Responsibility", kw_self_28: "Initiative", kw_self_29: "Let go of perfectionism",
    kw_self_30: "Leadership", kw_self_31: "Followership", kw_self_32: "Negotiation", kw_self_33: "Persuasion", kw_self_34: "Public speaking", kw_self_35: "Planning", kw_self_36: "Marketing", kw_self_37: "Personal branding", kw_self_38: "Networking", kw_self_39: "Mentoring", kw_self_40: "Benchmarking", kw_self_41: "Side project", kw_self_42: "Startup", kw_self_43: "Promotion", kw_self_44: "Salary negotiation",
    kw_self_45: "Savings", kw_self_46: "Investment", kw_self_47: "Stocks", kw_self_48: "Real estate", kw_self_49: "Spending control", kw_self_50: "Budget", kw_self_51: "Financial freedom", kw_self_52: "FIRE", kw_self_53: "Wealth building", kw_self_54: "Seed money", kw_self_55: "Compound interest", kw_self_56: "Asset allocation",
    kw_self_57: "Burnout", kw_self_58: "Slump", kw_self_59: "Failure", kw_self_60: "Rejection", kw_self_61: "Criticism", kw_self_62: "Stress", kw_self_63: "Insomnia", kw_self_64: "Procrastination", kw_self_65: "Three-day resolution", kw_self_66: "Inferiority", kw_self_67: "Jealousy", kw_self_68: "Lethargy", kw_self_69: "Trauma", kw_self_70: "Digital detox",
    kw_self_71: "Minimalist life", kw_self_72: "Work-life balance", kw_self_73: "Digital nomad", kw_self_74: "Side hustle", kw_self_75: "Lifelong learning", kw_self_76: "Language study", kw_self_77: "Certification", kw_self_78: "Hobby", kw_self_79: "Diet", kw_self_80: "Health",
    kw_hum_0: "Who am I", kw_hum_1: "Self", kw_hum_2: "Unconscious", kw_hum_3: "Desire", kw_hum_4: "Instinct", kw_hum_5: "Reason", kw_hum_6: "Emotion", kw_hum_7: "Memory", kw_hum_8: "Forgetting", kw_hum_9: "Dream", kw_hum_10: "Body", kw_hum_11: "Soul", kw_hum_12: "Death", kw_hum_13: "Aging", kw_hum_14: "Birth", kw_hum_15: "Growth", kw_hum_16: "Genius", kw_hum_17: "Madness",
    kw_hum_18: "Others", kw_hum_19: "Love", kw_hum_20: "Friendship", kw_hum_21: "Family", kw_hum_22: "Community", kw_hum_23: "Solitude", kw_hum_24: "Alienation", kw_hum_25: "Hatred", kw_hum_26: "Discrimination", kw_hum_27: "Equality", kw_hum_28: "Justice", kw_hum_29: "Law", kw_hum_30: "Power", kw_hum_31: "Politics", kw_hum_32: "War", kw_hum_33: "Peace", kw_hum_34: "Capitalism", kw_hum_35: "Labor", kw_hum_36: "Ownership",
    kw_hum_37: "Happiness", kw_hum_38: "Unhappiness", kw_hum_39: "Freedom", kw_hum_40: "Fate", kw_hum_41: "Chance", kw_hum_42: "Necessity", kw_hum_43: "Truth", kw_hum_44: "Falsehood", kw_hum_45: "Good and evil", kw_hum_46: "Morality", kw_hum_47: "Ethics", kw_hum_48: "Religion", kw_hum_49: "God", kw_hum_50: "Salvation", kw_hum_51: "Faith", kw_hum_52: "Doubt", kw_hum_53: "Hope", kw_hum_54: "Despair",
    kw_hum_55: "Time", kw_hum_56: "Eternity", kw_hum_57: "Moment", kw_hum_58: "Past", kw_hum_59: "Future", kw_hum_60: "Present", kw_hum_61: "History", kw_hum_62: "Universe", kw_hum_63: "Nature", kw_hum_64: "Environment", kw_hum_65: "Technology", kw_hum_66: "AI", kw_hum_67: "Artificial intelligence", kw_hum_68: "Virtual reality", kw_hum_69: "Evolution", kw_hum_70: "Extinction",
    kw_hum_71: "Beauty", kw_hum_72: "Ugliness", kw_hum_73: "Art", kw_hum_74: "Creation", kw_hum_75: "Destruction", kw_hum_76: "Inspiration", kw_hum_77: "Imitation", kw_hum_78: "Originality", kw_hum_79: "Taste", kw_hum_80: "Trend", kw_hum_81: "Classic", kw_hum_82: "Romantic", kw_hum_83: "Nihilism", kw_hum_84: "Absurdity", kw_hum_85: "Silence", kw_hum_86: "Language",
    ending_closed_happy: "Closed ending (Happy)",
    ending_closed_sad: "Closed ending (Tragic/Sad)",
    ending_open: "Open ending (Lingering)",
    ending_twist: "Twist ending (Shocking)",
    ending_bookend: "Bookend (Beginning & end connect)",
    ending_style: "Ending Style",
    ending_style_desc: "How should the story end?",
    back: "Back",
    no_select: "None",
    // Extra Write Modal
    extra_write_title: "Extra Write",
    extra_write_desc_2: "You used your free daily writes.",
    extra_write_confirm: "Use {cost} Ink to write more?",
    current_hold: "Current: {ink} Ink",
    ad_write_free: "Watch Ad to Write Free",
    or: "OR",
    // Promotion (duplicate section)
    promo_section_title: "Featured Books",
    promo_button: "Promote",
    promo_active: "Promoting",
    promo_modal_title: "Promote Book",
    promo_input_placeholder: "Enter promo text (max 50 chars)",
    promo_cost: "Costs 10 ink (48 hours)",
    promo_full: "All promo slots are full. Please try again later.",
    promo_already: "You already have a promoted book.",
    promo_ink_short: "Not enough ink (need: 10)",
    promo_remaining: "Time left",
    promo_confirm: "Start Promotion",
    promo_hours: "h",
    promo_minutes: "m",
    // Achievement
    achievement_title: "🏆 My Achievements",
    achievement_unlocked: "Achievement Unlocked!",
    achievement_locked: "Locked",
    ach_first_write_title: "First Write",
    ach_first_write_desc: "Wrote your first book",
    ach_writer_5_title: "Writer",
    ach_writer_5_desc: "Wrote 5 books",
    ach_writer_10_title: "Prolific Writer",
    ach_writer_10_desc: "Wrote 10 books",
    ach_first_read_title: "First Read",
    ach_first_read_desc: "Read someone else's book",
    ach_reader_5_title: "Reader",
    ach_reader_5_desc: "Read 5 books",
    ach_reader_10_title: "Avid Reader",
    ach_reader_10_desc: "Read 10 books",
    ach_streak_3_title: "3-Day Streak",
    ach_streak_3_desc: "Attended 3 days in a row",
    ach_streak_7_title: "7-Day Streak",
    ach_streak_7_desc: "Attended 7 days in a row",
    ach_level_10_title: "Level 10",
    ach_level_10_desc: "Reached level 10",
    ach_level_30_title: "Level 30",
    ach_level_30_desc: "Reached level 30",
    ach_comment_5_title: "Commenter",
    ach_comment_5_desc: "Posted 5 comments",
    ach_ink_100_title: "Ink Master",
    ach_ink_100_desc: "Used 100 drops of ink"
  }
};

// 장르 데이터 (genres)
export const genres = [
  {
    id: 'fiction',
    nameKey: 'fiction',
    icon: <BookOpen className="w-5 h-5" />,
    color: 'bg-blue-100 text-blue-600',
    prompt: '일상적이고 따뜻한 단편 소설을 써줘.',
    hasSubGenre: true,
    subGenres: [
      { id: 'daily', name: '일상', icon: <Coffee className="w-5 h-5" />, prompt: '소소하고 따뜻한 일상 속의 이야기를 담백하게 써주세요.' },
      { id: 'emotion', name: '감정', icon: <Heart className="w-5 h-5" />, prompt: '인물의 섬세한 감정선을 따라가는 깊이 있는 이야기를 써주세요.' },
      { id: 'twist', name: '반전', icon: <Zap className="w-5 h-5" />, prompt: '평범하게 시작하지만 마지막에 놀라운 반전이 있는 이야기를 써주세요.' },
      { id: 'healing', name: '힐링', icon: <Smile className="w-5 h-5" />, prompt: '지친 마음을 위로해주는 따뜻하고 몽글몽글한 이야기를 써주세요.' },
      { id: 'series', name: '시리즈', icon: <Library className="w-5 h-5" />, prompt: '다음 화가 궁금해지는 몰입감 높은 연재 소설을 써주세요. (주제 랜덤)' }
    ]
  },
  {
    id: 'essay',
    nameKey: 'essay',
    icon: <Coffee className="w-5 h-5" />,
    color: 'bg-orange-100 text-orange-600',
    prompt: '친구에게 말하듯 편안한 에세이를 써줘.',
    hasSubGenre: true,
    subGenres: [
      { id: 'empathy', name: '공감위로', icon: <Heart className="w-5 h-5" />, prompt: '힘든 하루를 보낸 이에게 건네는 따뜻한 위로의 글을 써주세요.' },
      { id: 'attitude', name: '삶의태도', icon: <PenTool className="w-5 h-5" />, prompt: '삶을 대하는 긍정적이고 성찰적인 태도에 대해 써주세요.' },
      { id: 'relation', name: '관계', icon: <User className="w-5 h-5" />, prompt: '가족, 친구, 연인 등 사람 사이의 관계에 대한 깊은 통찰을 담아주세요.' },
      { id: 'alone', name: '혼자만의 시간', icon: <MoonIcon className="w-5 h-5" />, prompt: '고독을 즐기는 법과 혼자 있는 시간의 소중함에 대해 써주세요.' }
    ]
  },
  {
    id: 'improvement',
    nameKey: 'improvement',
    icon: <Lightbulb className="w-5 h-5" />,
    color: 'bg-green-100 text-green-600',
    prompt: '현실적인 자기계발 조언을 해줘.',
    hasSubGenre: true,
    subGenres: [
      { id: 'habit', name: '습관·루틴', icon: <RefreshCw className="w-5 h-5" />, prompt: '성공적인 삶을 위한 작은 습관과 루틴 형성법에 대해 조언해주세요.' },
      { id: 'mindset', name: '마인드셋', icon: <Brain className="w-5 h-5" />, prompt: '단단한 멘탈과 긍정적인 사고방식을 갖기 위한 마인드셋을 이야기해주세요.' },
      { id: 'communication', name: '인간관계·소통', icon: <MessageCircle className="w-5 h-5" />, prompt: '타인과 원활하게 소통하고 좋은 관계를 맺는 대화법과 처세술을 알려주세요.' },
      { id: 'life', name: '인생정리', icon: <List className="w-5 h-5" />, prompt: '복잡한 인생을 단순하게 정리하고 중요한 것에 집중하는 법을 알려주세요.' }
    ]
  },
  {
    id: 'humanities',
    nameKey: 'humanities',
    icon: <Brain className="w-5 h-5" />,
    color: 'bg-purple-100 text-purple-600',
    prompt: '쉬운 인문학 이야기를 해줘.',
    hasSubGenre: true,
    subGenres: [
      { id: 'psychology', name: '생활형심리', icon: <Heart className="w-5 h-5" />, prompt: '일상 생활에서 겪는 문제들을 심리학적 관점에서 쉽고 재미있게 풀어주세요.' },
      { id: 'philosophy', name: '이야기철학', icon: <Book className="w-5 h-5" />, prompt: '어려운 철학 개념을 재미있는 옛날 이야기나 예시를 들어 쉽게 설명해주세요.' },
      { id: 'human', name: '인간이해', icon: <User className="w-5 h-5" />, prompt: '인간의 본성과 행동 원리에 대한 인문학적 통찰을 쉽게 전달해주세요.' },
      { id: 'thinking', name: '생각훈련', icon: <Lightbulb className="w-5 h-5" />, prompt: '논리적으로 생각하고 비판적으로 사고하는 힘을 기르는 방법을 알려주세요.' }
    ]
  }
];